"use client";
import * as React from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { archiveStudents,schoolResearchSummary,type ArchiveFilter } from "@/lib/admin-analytics";
import { studentWorkspaceUrl } from "@/lib/admin-overview";
import type { PortalData } from "@/lib/portal-types";
import type { ProfileImport } from "@/lib/profile-import";
import { OperationHistory } from "@/app/admin-operations";
const card="rounded-2xl border border-[#dfe6ef] bg-white p-5";
const select="h-11 w-full rounded-lg border border-[#d8e1ec] bg-white px-3 text-sm";
const defaults:ArchiveFilter={query:"",schoolYear:"all",status:"all",graduatedYear:"all"};
function Filters({data,value,onChange}:{data:PortalData;value:ArchiveFilter;onChange:(v:ArchiveFilter)=>void}){
  const years=[...new Set(data.classes.map(c=>c.schoolYear))].sort((a,b)=>b-a),graduates=[...new Set(data.students.map(s=>s.graduatedYear).filter((y):y is number=>y!==null))].sort((a,b)=>b-a);
  return <section className={card}><div className="grid gap-4 md:grid-cols-4"><label className="space-y-2 text-sm"><span className="block">이름·학번·연구 키워드</span><Input className="h-11" value={value.query} onChange={e=>onChange({...value,query:e.target.value})} placeholder="예: 생명과학"/></label><label className="space-y-2 text-sm"><span className="block">현재·최종 학급 학년도</span><select className={select} value={value.schoolYear} onChange={e=>onChange({...value,schoolYear:e.target.value})}><option value="all">전체 학년도</option>{years.map(y=><option key={y} value={y}>{y}학년도</option>)}</select></label><label className="space-y-2 text-sm"><span className="block">재학 상태</span><select className={select} value={value.status} onChange={e=>onChange({...value,status:e.target.value,graduatedYear:"all"})}><option value="all">재학·졸업·보관 전체</option><option value="active">재학생</option><option value="graduated">졸업생</option><option value="archived">보관 학생</option></select></label><label className="space-y-2 text-sm"><span className="block">졸업 연도</span><select className={select} value={value.graduatedYear} onChange={e=>onChange({...value,graduatedYear:e.target.value,status:e.target.value==="all"?value.status:"graduated"})}><option value="all">전체 졸업 연도</option>{graduates.map(y=><option key={y} value={y}>{y}년</option>)}</select></label></div><div className="mt-3 flex items-center justify-between gap-3"><p className="text-sm leading-6 text-[#596d85]">예시 학생 제외 · 검색 범위: 이름·학번, 모든 버전의 요약, 활성 분석의 키워드</p><Button size="sm" variant="ghost" onClick={()=>onChange({...defaults})}>조건 초기화</Button></div></section>;
}
export function AdminResearch({data,onKeyword}:{data:PortalData;onKeyword:(keyword:string)=>void}){
  const [filter,setFilter]=React.useState<ArchiveFilter>({...defaults,status:"active"});
  const members=archiveStudents(data,filter),summary=schoolResearchSummary(data,members),max=Math.max(1,summary.studentCount);
  return <div className="space-y-5"><Filters data={data} value={filter} onChange={setFilter}/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[{label:"선택한 학생",value:summary.studentCount,unit:"명"},{label:"활성 분석이 있는 학생",value:summary.profileCount,unit:"명"},{label:"보존된 분석 버전",value:summary.versionCount,unit:"개"},{label:"등록된 학생부 원본",value:summary.recordCount,unit:"개"}].map(m=><article key={m.label} className={card}><p className="text-sm text-[#596d85]">{m.label}</p><p className="mt-3 text-3xl font-bold">{m.value}<span className="ml-1 text-sm font-normal">{m.unit}</span></p></article>)}</div>
    <div className="grid gap-5 xl:grid-cols-2"><section className={card}><h2 className="text-lg font-bold">학교의 연구 키워드</h2><p className="mt-2 text-sm leading-6 text-[#596d85]">활성 분석에 등장한 키워드별 학생 수입니다. 같은 학생은 한 번만 셉니다. 키워드를 누르면 전체 누적 기록에서 검색합니다.</p><div className="mt-5 space-y-3">{summary.keywords.slice(0,15).map(k=><button key={k.keyword} className="block w-full rounded-lg p-2 text-left hover:bg-[#f4f7fb] focus-visible:outline-2" onClick={()=>onKeyword(k.keyword)}><span className="flex justify-between gap-3 text-sm"><span className="font-medium">{k.keyword}</span><span>{k.count}명</span></span><span className="mt-2 block h-2 rounded bg-[#edf2f8]"><span className="block h-2 rounded bg-[#2457d6]" style={{width:`${k.count/max*100}%`}}/></span></button>)}</div>{!summary.keywords.length&&<p className="py-8 text-sm text-[#596d85]">해당 학생들의 연구 키워드가 아직 등록되지 않았습니다.</p>}<p className="mt-4 text-xs text-[#65768b]">전체 {summary.keywordCount}개 중 최대 15개 · 학생 역량의 순위나 합격 예측이 아닙니다.</p></section>
    <section className={card}><h2 className="text-lg font-bold">기록 학년도별 자료 축적</h2><p className="mt-2 text-sm leading-6 text-[#596d85]">선택한 학생 중 해당 학년도 자료가 있는 학생 수입니다. 활동·교과는 활성 분석에 포함된 항목을 기준으로 셉니다.</p><div className="mt-5 space-y-5">{summary.years.map(y=><div key={y.year}><h3 className="font-semibold">{y.year}학년도</h3><div className="mt-3 space-y-2">{[{name:"학생부 원본",value:y.records,color:"#2457d6"},{name:"활동 항목",value:y.activities,color:"#13816d"},{name:"교과 기록",value:y.courses,color:"#9271be"}].map(b=><div key={b.name} className="grid grid-cols-[84px_1fr_40px] items-center gap-3 text-sm"><span>{b.name}</span><span className="h-2 rounded bg-[#edf2f8]"><span className="block h-2 rounded" style={{width:`${b.value/max*100}%`,background:b.color}}/></span><span className="text-right">{b.value}명</span></div>)}</div></div>)}</div>{!summary.years.length&&<p className="py-8 text-sm text-[#596d85]">원본이나 분석을 등록하면 기록 학년도별 현황이 표시됩니다.</p>}<p className="mt-5 text-xs leading-5 text-[#65768b]">0명은 등록된 자료가 없다는 뜻입니다. 활동을 하지 않았거나 성취가 낮다는 의미가 아닙니다.</p></section></div>
    <section className={card}><h2 className="text-lg font-bold">학급별 자료 준비</h2><div className="mt-4 overflow-auto"><table className="w-full min-w-[600px] text-left text-sm"><caption className="sr-only">선택 범위의 학급별 자료 등록 현황</caption><thead className="bg-[#edf2f8]"><tr>{["현재·최종 학급","학생","기본 학생부 준비","활성 분석","교과 기록 있음"].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{summary.classes.map(c=><tr key={c.id} className="border-b"><td className="p-3">{c.label}</td>{[c.students,c.records,c.profiles,c.academics].map((n,i)=><td key={i} className="p-3">{n}명</td>)}</tr>)}</tbody></table></div>{!summary.classes.length&&<p className="py-5 text-sm text-[#596d85]">해당하는 학생이 없습니다.</p>}</section></div>;
}
function ArchivedVersion({id}:{id:number}){
  const [value,setValue]=React.useState<{profile:ProfileImport|null;warning:string|null}|null>(null),[error,setError]=React.useState(""),[retry,setRetry]=React.useState(0);
  React.useEffect(()=>{const abort=new AbortController();setValue(null);setError("");fetch(`/api/admin/archive?snapshotId=${id}`,{cache:"no-store",signal:abort.signal}).then(async r=>{const data=await r.json() as {profile:ProfileImport|null;warning:string|null;error?:string};if(!r.ok)throw new Error(data.error||"분석을 열지 못했습니다.");return data;}).then(setValue).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[id,retry]);
  if(error)return <div role="alert" className="mt-4 space-y-3 text-sm"><p>{error}</p><Button variant="outline" onClick={()=>setRetry(x=>x+1)}>다시 불러오기</Button></div>;
  if(!value)return <p className="mt-4 text-sm" role="status">저장된 분석 버전을 불러옵니다.</p>;
  const p=value.profile;
  return <div className="mt-5 space-y-5"><Button variant="outline" asChild><a href={`/api/admin/archive?snapshotId=${id}&download=1`}>이 버전 JSON 다운로드</a></Button>{value.warning&&<p className="text-sm leading-6">{value.warning}</p>}{p&&<>
    <div><h4 className="font-semibold">당시 연구 프로필</h4><p className="mt-2 text-sm leading-7 whitespace-pre-wrap">{p.overview.narrative}</p><div className="mt-3 flex flex-wrap gap-2">{p.researchFingerprint.map((k,i)=><span key={i} title={k.description} className="rounded-full bg-[#eaf0fe] px-3 py-2 text-sm text-[#2457d6]">{k.keyword}</span>)}</div></div>
    <div className="rounded-lg bg-[#f4f7fb] p-4 text-sm leading-7">활동 항목 {p.sections.length}개 · 교과 기록 {p.academicAnalysis.courses.length}개 · 위키 문서 {p.wikiPages.length}개<br/>포함 학년도 {p.sourceYears.join(", ")}</div>
    <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">활동별 목차와 근거</summary><div className="mt-4 space-y-4">{p.sections.map(s=><article key={s.id} className="border-t pt-3"><p className="text-xs text-[#65768b]">{s.schoolYear} · {s.subject||"창체·기타"}</p><h5 className="mt-1 font-semibold">{s.title}</h5><p className="mt-2 text-sm leading-7">{s.summary}</p>{s.evidence.map((e,i)=><blockquote key={i} className="mt-2 border-l-2 pl-3 text-sm leading-6 text-[#596d85]">{e}</blockquote>)}{s.recordId&&<a className="mt-2 inline-block text-sm underline" href={`/api/student-records/${s.recordId}`} target="_blank" rel="noreferrer">연결 원본 {s.page?`${s.page}쪽`:"열기"}</a>}</article>)}</div></details>
    <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">교과·성적·학점 기록</summary><div className="mt-4 overflow-auto"><table className="w-full min-w-[540px] text-left text-sm"><thead><tr>{["학년도·학기","과목","이수 상태","학점","등급 / 성취도"].map(h=><th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{p.academicAnalysis.courses.map((c,i)=><tr key={i} className="border-t"><td className="p-2">{c.schoolYear} · {c.semester}학기</td><td className="p-2">{c.subject}</td><td className="p-2">{{completed:"이수",selected:"선택",planned:"계획"}[c.selectionStatus]}</td><td className="p-2">{c.credits??"미확인"}</td><td className="p-2">{c.rankGrade||"—"} / {c.achievement||"—"}</td></tr>)}</tbody></table></div></details>
    <details className="rounded-lg border p-4"><summary className="cursor-pointer font-medium">연구 위키 문서</summary><div className="mt-4 space-y-4">{p.wikiPages.map(w=><article key={w.slug} className="border-t pt-3"><h5 className="font-semibold">{w.title}</h5><p className="mt-2 text-sm leading-6">{w.summary}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-7">{w.bodyMarkdown}</p></article>)}</div></details>
  </>}</div>;
}
export function AdminArchive({data,initialQuery=""}:{data:PortalData;initialQuery?:string}){
  const [filter,setFilter]=React.useState<ArchiveFilter>({...defaults,query:initialQuery}),[studentId,setStudentId]=React.useState<number|null>(null),[snapshotId,setSnapshotId]=React.useState<number|null>(null),[page,setPage]=React.useState(1);
  const matches=archiveStudents(data,filter),count=Math.max(1,Math.ceil(matches.length/30)),current=Math.min(page,count),rows=matches.slice((current-1)*30,current*30),student=matches.find(s=>s.id===studentId),versions=data.profileSnapshots.filter(p=>p.studentId===student?.id).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id-a.id);
  const change=(v:ArchiveFilter)=>{setFilter(v);setPage(1);setStudentId(null);setSnapshotId(null);};
  return <div className="space-y-5"><Filters data={data} value={filter} onChange={change}/><div className="grid items-start gap-5 xl:grid-cols-[minmax(280px,1fr)_minmax(0,2fr)]"><section className={card}><h2 className="font-bold">검색 결과 {matches.length}명</h2><div className="mt-4 space-y-2">{rows.map(s=>{const cls=data.classes.find(c=>c.id===s.classId);return <button key={s.id} className={`w-full rounded-xl border p-4 text-left ${student?.id===s.id?"border-[#2457d6] bg-[#eef3ff]":"hover:bg-[#f4f7fb]"}`} aria-pressed={student?.id===s.id} onClick={()=>{setStudentId(s.id);setSnapshotId(null);}}><span className="font-semibold">{s.name}</span><span className="ml-2 text-sm">{s.studentNumber}</span><span className="mt-2 block text-xs leading-5 text-[#65768b]">{cls?.schoolYear} · {cls?.name} · {s.status==="graduated"?`${s.graduatedYear??""}년 졸업`:s.status==="archived"?"보관":"재학"}</span><span className="mt-2 block text-sm">분석 {data.profileSnapshots.filter(p=>p.studentId===s.id).length}개 · 원본 {data.records.filter(r=>r.studentId===s.id).length}개</span></button>;})}</div>{!rows.length&&<p className="py-6 text-sm text-[#596d85]">조건에 맞는 학생이 없습니다.</p>}<div className="mt-4 flex items-center justify-between text-sm"><Button variant="ghost" disabled={current===1} onClick={()=>setPage(current-1)}>이전</Button><span>{current} / {count}</span><Button variant="ghost" disabled={current===count} onClick={()=>setPage(current+1)}>다음</Button></div></section>
    <div className="min-w-0 space-y-5">{student?<><section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{student.name}의 누적 기록</h2><Button variant="outline" asChild><a href={studentWorkspaceUrl(student.id,"records")}>원본·현재 분석 열기</a></Button></div><p className="mt-3 text-sm leading-6 text-[#596d85]">학생 ID {student.id} · 같은 ID로 진급·졸업 전후 자료를 이어서 보존합니다. 아래에서 열람하는 이전 버전은 현재 분석을 바꾸지 않습니다.</p><div className="mt-5 space-y-4">{versions.map(v=><article key={v.id} className="rounded-xl border p-4"><p className="text-xs text-[#65768b]">{v.createdAt.slice(0,10)} · {v.isActive?"현재 활성 분석":"보존된 이전 분석"}</p><h3 className="mt-2 font-semibold">{v.versionLabel}</h3><p className="mt-2 text-sm leading-6">{v.oneLineProfile}</p><p className="mt-2 text-xs text-[#65768b]">포함 학년도 {v.sourceYears.join(", ")}</p><Button className="mt-3" size="sm" variant="outline" aria-expanded={snapshotId===v.id} onClick={()=>setSnapshotId(snapshotId===v.id?null:v.id)}>{snapshotId===v.id?"상세 닫기":"이 버전 상세 보기"}</Button>{snapshotId===v.id&&<ArchivedVersion key={v.id} id={v.id}/>}</article>)}</div>{!versions.length&&<p className="py-6 text-sm text-[#596d85]">등록된 분석 버전이 없습니다. 학생부 원본과 활동은 학생 자료 열람에서 확인할 수 있습니다.</p>}</section><OperationHistory key={student.id} studentId={student.id}/></>:<section className={`${card} py-16 text-center`}><h2 className="text-lg font-bold">학생의 연구 흐름을 이어서 살펴보세요</h2><p className="mt-3 text-sm leading-7 text-[#596d85]">명단에서 학생을 선택하면 이전 분석 버전과 학적 변경 이력을 확인할 수 있습니다.</p></section>}</div></div></div>;
}
