"use client";
import * as React from "react";
import { clientId } from "@/lib/client-id";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle,DialogFooter } from "@/components/ui/dialog";
import { operationLabels,type OperationKind } from "@/lib/admin-operation-types";
import type { OperationPreview,OperationEvent } from "@/lib/admin-operations";
import type { PortalData } from "@/lib/portal-types";
const select="h-11 w-full rounded-lg border border-[#d8e1ec] bg-white px-3 text-sm";
const card="rounded-2xl border border-[#dfe6ef] bg-white p-5";
async function operationRequest<T>(body:unknown,signal?:AbortSignal):Promise<T>{const r=await fetch("/api/admin/operations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal});const data=await r.json() as T & {error?:string};if(!r.ok)throw new Error(data.error||"작업을 처리하지 못했습니다.");return data;}
export function OperationReview({input,onClose,onSaved,disabled=false}:{input:Record<string,unknown>;onClose:()=>void;onSaved:()=>Promise<void>;disabled?:boolean}){
  const [preview,setPreview]=React.useState<OperationPreview|null>(null),[error,setError]=React.useState(""),[busy,setBusy]=React.useState(false),[confirmed,setConfirmed]=React.useState(false),[retry,setRetry]=React.useState(0);
  const lock=React.useRef(false),serialized=JSON.stringify(input);
  React.useEffect(()=>{const abort=new AbortController();setPreview(null);setError("");setConfirmed(false);operationRequest<OperationPreview>({intent:"preview",input:JSON.parse(serialized)},abort.signal).then(setPreview).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[serialized,retry]);
  const commit=async()=>{
    if(!preview||!confirmed||lock.current||disabled)return;lock.current=true;setBusy(true);setError("");
    try{const result=await operationRequest<{count:number}>({intent:"commit",input:preview.input,token:preview.token});toast.success(`${result.count}건의 변경과 이력을 저장했습니다.`);await onSaved();onClose();}
    catch(e){setError(e instanceof Error?e.message:"저장 결과를 확인하지 못했습니다. 이력과 목록을 새로고침하세요.");setPreview(null);setConfirmed(false);}
    finally{lock.current=false;setBusy(false);}
  };
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent className="sm:max-w-3xl max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>변경 내용 최종 확인</DialogTitle><DialogDescription>명단·변경 전후·사유를 확인한 뒤 저장합니다.</DialogDescription></DialogHeader>
    {error?<div role="alert" className="space-y-3 rounded-lg bg-amber-50 p-4 text-sm leading-6"><p>{error}</p><Button variant="outline" onClick={()=>setRetry(x=>x+1)}>다시 확인</Button></div>:!preview?<p role="status">현재 자료를 확인하고 있습니다.</p>:<>
      <p className="text-sm leading-6">{preview.message}</p><p className="rounded-lg bg-[#f1f5fb] p-3 text-sm">{operationLabels[preview.input.kind]} · {preview.rows.length}건<br/>사유: {preview.input.reason}</p>
      <div className="max-h-72 overflow-auto rounded-lg border"><table className="min-w-[540px] w-full text-left text-sm"><caption className="sr-only">변경 미리보기</caption><thead className="sticky top-0 bg-[#edf2f8]"><tr>{["대상","변경 전","변경 후"].map(t=><th key={t} className="p-3">{t}</th>)}</tr></thead><tbody>{preview.rows.map(r=><tr key={r.targetId} className="border-t"><td className="p-3 font-medium">{r.name}</td><td className="p-3">{r.beforeLabel}</td><td className="p-3">{r.afterLabel}</td></tr>)}</tbody></table></div>
      <label className="flex min-h-11 items-center gap-3 text-sm"><Checkbox checked={confirmed} onCheckedChange={v=>setConfirmed(v===true)} disabled={busy}/>대상과 변경 내용을 확인했습니다.</label>
    </>}
    <DialogFooter><Button variant="outline" disabled={busy} onClick={onClose}>닫기</Button><Button disabled={!preview||!confirmed||busy||disabled} onClick={()=>void commit()}>{busy?"저장 중…":"확인한 내용 저장"}</Button></DialogFooter>
  </DialogContent></Dialog>;
}
export function AdminOperations({data,disabled,onSaved}:{data:PortalData;disabled:boolean;onSaved:()=>Promise<void>}){
  const [kind,setKind]=React.useState<Exclude<OperationKind,"assign_teacher">>("promote"),[source,setSource]=React.useState(""),[target,setTarget]=React.useState(""),[year,setYear]=React.useState("");
  const [selected,setSelected]=React.useState<number[]>([]),[numbers,setNumbers]=React.useState<Record<number,string>>({}),[reason,setReason]=React.useState(""),[start,setStart]=React.useState("001"),[input,setInput]=React.useState<Record<string,unknown>|null>(null);
  const cls=data.classes.find(c=>c.id===Number(source)),moving=kind==="promote"||kind==="transfer";
  const eligible=data.students.filter(s=>!s.isExample&&s.classId===Number(source)&&(kind==="restore"?s.status!=="active":s.status==="active")).sort((a,b)=>a.studentNumber.localeCompare(b.studentNumber,"ko",{numeric:true}));
  const selectedRows=eligible.filter(s=>selected.includes(s.id));
  const reset=()=>{setSelected([]);setNumbers({});setTarget("");};
  const targets=data.classes.filter(c=>cls&&(kind==="promote"?c.grade===3&&c.schoolYear===cls.schoolYear+1:c.grade===cls.grade&&c.schoolYear===cls.schoolYear&&c.id!==cls.id));
  const fillNumbers=()=>{if(!/^\d{1,15}$/.test(start)){toast.error("시작 학번을 15자리 이내 숫자로 입력하세요.");return;}const first=Number(start);setNumbers(Object.fromEntries(selectedRows.map((s,i)=>[s.id,String(first+i).padStart(start.length,"0")])));};
  return <div className="space-y-5"><section className={card}><h2 className="text-lg font-bold">학년도 전환과 학적 변경</h2><p className="mt-2 text-sm leading-6 text-[#596d85]">진급할 새 학급은 ‘학급·담임 배정’에서 먼저 만드세요. 한 번에 100명까지 처리하며 예시 학생은 제외합니다. 현재 학급 변경 후에는 새 담임이 이전 기록까지 이어서 관리합니다.</p>
    <div className="mt-5 grid gap-4 md:grid-cols-3"><label className="space-y-2 text-sm"><span className="block">작업</span><select className={select} value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setSource("");reset();}}>{(["promote","transfer","graduate","restore"] as const).map(k=><option key={k} value={k}>{operationLabels[k]}</option>)}</select></label>
      <label className="space-y-2 text-sm"><span className="block">현재 학급</span><select className={select} value={source} onChange={e=>{setSource(e.target.value);reset();const c=data.classes.find(c=>c.id===Number(e.target.value));setYear(c?String(c.schoolYear+1):"");}}><option value="">학급 선택</option>{data.classes.filter(c=>kind==="promote"?c.grade===2:kind==="graduate"?c.grade===3:true).map(c=><option key={c.id} value={c.id}>{c.schoolYear} · {c.name}</option>)}</select></label>
      {moving?<label className="space-y-2 text-sm"><span className="block">변경할 학급</span><select className={select} value={target} onChange={e=>setTarget(e.target.value)}><option value="">학급 선택</option>{targets.map(c=><option key={c.id} value={c.id}>{c.schoolYear} · {c.name}</option>)}</select></label>:kind==="graduate"?<label className="space-y-2 text-sm"><span className="block">졸업 연도</span><Input className="h-11" type="number" value={year} min={2022} max={2100} onChange={e=>setYear(e.target.value)}/></label>:<p className="self-end text-sm leading-6 text-[#596d85]">졸업·보관 처리를 정정하여 기존 학급의 재학생으로 돌립니다.</p>}
    </div>{moving&&source&&!targets.length&&<p className="mt-4 text-sm text-amber-800">조건에 맞는 새 학급이 없습니다. 학급·담임 배정에서 {kind==="promote"?"다음 학년도 3학년":"같은 학년도·학년"} 학급을 추가하세요.</p>}
  </section>
  <section className={card}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">대상 명단 · {selectedRows.length}명 선택</h2><div className="flex gap-2"><Button size="sm" variant="outline" disabled={!eligible.length} onClick={()=>setSelected(eligible.slice(0,100).map(s=>s.id))}>앞에서 100명까지 선택</Button><Button size="sm" variant="ghost" onClick={()=>setSelected([])}>선택 해제</Button></div></div>
    {moving&&<div className="mt-4 flex flex-wrap items-end gap-3"><label className="space-y-2 text-sm"><span className="block">새 학번 시작값</span><Input className="w-36 h-11" value={start} onChange={e=>setStart(e.target.value)} placeholder="001"/></label><Button variant="outline" disabled={!selectedRows.length} onClick={fillNumbers}>선택 학생 연속 학번 채우기</Button><p className="text-sm text-[#596d85]">목록 순서로 채우며 앞자리 0을 유지합니다. 개별 수정도 가능합니다.</p></div>}
    <div className="mt-4 max-h-[460px] overflow-auto"><table className="w-full min-w-[500px] text-left text-sm"><caption className="sr-only">학적 변경 대상 학생</caption><thead className="sticky top-0 bg-[#edf2f8]"><tr>{["선택","현재 학번","이름",moving?"새 학번":"현재 상태"].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{eligible.map(s=><tr key={s.id} className="border-b"><td className="p-2"><label className="flex min-h-11 w-11 items-center justify-center"><Checkbox aria-label={`${s.name} 선택`} checked={selected.includes(s.id)} disabled={!selected.includes(s.id)&&selectedRows.length>=100} onCheckedChange={v=>setSelected(prev=>v===true?[...prev,s.id]:prev.filter(id=>id!==s.id))}/></label></td><td className="p-3">{s.studentNumber}</td><td className="p-3">{s.name}</td><td className="p-3">{moving?<Input aria-label={`${s.name} 새 학번`} disabled={!selected.includes(s.id)} value={numbers[s.id]??s.studentNumber} maxLength={30} onChange={e=>setNumbers(prev=>({...prev,[s.id]:e.target.value}))}/>:s.status==="active"?"재학":s.status==="graduated"?"졸업":"보관"}</td></tr>)}</tbody></table></div>
    {!eligible.length&&<p className="py-6 text-sm text-[#596d85]">{source?"이 작업에 해당하는 실제 학생이 없습니다.":"현재 학급을 선택하면 학생 명단이 표시됩니다."}</p>}
    <label className="mt-5 block space-y-2 text-sm"><span className="block">변경 사유</span><textarea className="min-h-24 w-full rounded-lg border p-3" value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder="예: 2027학년도 3학년 학급 편성에 따른 진급"/></label>
    <div className="mt-4 flex justify-end"><Button disabled={disabled||!selectedRows.length||reason.trim().length<2||(moving&&!target)} onClick={()=>setInput({batchId:clientId(),kind,reason,targets:selectedRows.map(s=>({studentId:s.id,...(moving?{studentNumber:numbers[s.id]??s.studentNumber}:{})})),...(moving?{classId:Number(target)}:{}),...(kind==="graduate"?{graduatedYear:Number(year)}:{})})}>변경 내용 미리보기</Button></div>
  </section>{input&&<OperationReview input={input} disabled={disabled} onClose={()=>setInput(null)} onSaved={async()=>{await onSaved();setSelected([]);setNumbers({});setReason("");}}/>}</div>;
}
export function OperationHistory({studentId,refreshKey=0}:{studentId?:number;refreshKey?:number}){
  const [events,setEvents]=React.useState<OperationEvent[]>([]),[next,setNext]=React.useState<number|null>(null),[kind,setKind]=React.useState(""),[query,setQuery]=React.useState(""),[search,setSearch]=React.useState(""),[error,setError]=React.useState(""),[busy,setBusy]=React.useState(false),[retry,setRetry]=React.useState(0);
  const generation=React.useRef(0),lock=React.useRef(false);
  const load=React.useCallback(async(cursor=0)=>{if(cursor&&lock.current)return;const gen=++generation.current;lock.current=true;setBusy(true);setError("");try{const params=new URLSearchParams({kind,q:search});if(studentId)params.set("studentId",String(studentId));if(cursor)params.set("cursor",String(cursor));const r=await fetch(`/api/admin/operations?${params}`,{cache:"no-store"});const result=await r.json() as {events:OperationEvent[];nextCursor:number|null;error?:string};if(!r.ok)throw new Error(result.error||"이력을 읽지 못했습니다.");if(gen===generation.current){setEvents(prev=>cursor?[...prev,...result.events]:result.events);setNext(result.nextCursor);}}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:"이력을 읽지 못했습니다.");}finally{if(gen===generation.current){setBusy(false);lock.current=false;}}},[kind,search,studentId]);
  React.useEffect(()=>{setEvents([]);setNext(null);void load();return()=>{generation.current++;};},[load,refreshKey,retry]);
  function label(json:string){try{const row=JSON.parse(json);return {name:row.name??"",label:row.label??""};}catch{return {name:"",label:"이전 형식"};}}
  return <section className={card}><h2 className="text-lg font-bold">학적·담임 변경 이력</h2><p className="mt-2 text-sm leading-6 text-[#596d85]">6단계 관리자 변경 기능에서 저장한 이력입니다. 처리자·사유·변경 전후를 보존합니다. 이전의 개별 변경은 누적 자료에 별도로 남아 있을 수 있습니다.</p>
    <form className="mt-4 flex flex-wrap gap-3" onSubmit={e=>{e.preventDefault();setSearch(query.trim());}}><select aria-label="변경 종류" className={`${select} max-w-48`} value={kind} onChange={e=>setKind(e.target.value)}><option value="">전체 변경</option>{Object.entries(operationLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><Input aria-label="이름·처리자·사유 검색" className="h-11 max-w-xs" value={query} onChange={e=>setQuery(e.target.value)} placeholder="이름·처리자·사유 검색"/><Button type="submit" variant="outline">검색</Button><Button type="button" variant="ghost" disabled={busy} onClick={()=>setRetry(x=>x+1)}>새로고침</Button></form>
    {error&&<p role="alert" className="mt-4 text-sm text-amber-800">{error}</p>}
    <div className="mt-4 space-y-3">{events.map(e=><article key={e.id} className="rounded-xl border p-4 text-sm"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{operationLabels[e.kind]} · {label(e.beforeJson).name}</p><time className="text-[#65768b]">{e.createdAt.replace("T"," ").replace(/\.\d+Z$/," UTC")}</time></div><p className="mt-3">변경 전: {label(e.beforeJson).label}</p><p className="mt-1">변경 후: {label(e.afterJson).label}</p><p className="mt-3 text-[#596d85]">{e.actorName} · {e.reason}</p><p className="mt-2 text-xs text-[#65768b]">작업 번호 {e.batchId.slice(0,8)} · 대상 ID {e.targetId}</p></article>)}</div>
    {!events.length&&!busy&&!error&&<p className="py-6 text-sm text-[#596d85]">조건에 맞는 변경 이력이 없습니다.</p>}{busy&&<p role="status" className="py-4 text-sm">이력을 불러옵니다.</p>}{next&&<Button className="mt-4" variant="outline" disabled={busy} onClick={()=>void load(next)}>이전 이력 더 보기</Button>}
  </section>;
}
