"use client";
import * as React from "react";
import { History,Printer,Search,ArrowRight } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import { Tabs,TabsContent,TabsList,TabsTrigger } from "@/components/ui/tabs";
import type { CompetencyEvaluation,PortalData,ProfileSnapshot,Student } from "@/lib/portal-types";
import type { profileDifference } from "@/lib/profile-evidence";
import { calculateCredits } from "@/lib/profile-evidence";
import { gradingSystems } from "@/lib/guidance";
import { Choice } from "@/app/guidance-view";
import { EvidenceButton,SourceCard } from "@/app/evidence-panel";
import { LinkedMarkdown } from "@/app/linked-markdown";
import { AcademicTrendChart } from "@/app/academic-trend-chart";

type Props={data:PortalData;students:Student[];selectedStudentId:number|null;onSelect:(id:number)=>void};
function selectedId(p:Props){return p.students.find(s=>s.id===p.selectedStudentId)?.id??p.students[0]?.id??0;}
function Top({p,title,description}:{p:Props;title:string;description:string}){return <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{title}</h1><p className="mt-3 max-w-3xl text-base leading-7 text-[#65768b]">{description}</p></div>{p.students.length>0&&<div className="w-full sm:w-64"><Choice label="학생 선택" value={String(selectedId(p))} onChange={v=>p.onSelect(Number(v))} items={p.students.map(s=>[String(s.id),`${s.name} · ${s.studentNumber}`])}/></div>}</div>;}
function Empty({children}:{children:React.ReactNode}){return <div className="rounded-2xl border border-dashed bg-white p-8 text-base leading-7 text-[#65768b]">{children}</div>;}

export function AcademicsView(p:Props){
  const id=selectedId(p),{data}=p,profile=data.profileSnapshots.find(s=>s.studentId===id&&s.isActive),courses=data.academicCourses.filter(c=>c.studentId===id&&c.snapshotId===profile?.id),trends=data.academicTrends.filter(c=>c.studentId===id&&c.snapshotId===profile?.id),groups=calculateCredits(courses);
  const summaries=data.creditSummaries.filter(c=>c.studentId===id&&c.snapshotId===profile?.id);
  const status={completed:"이수 완료",selected:"선택·수강",planned:"향후 계획"};
  return <><Top p={p} title="교과·성적·실제 이수학점" description="완료한 학점과 선택·계획을 구분합니다. 성적은 적용 체계와 원문을 함께 확인하세요."/>{!courses.length&&!trends.length&&!summaries.length?<Empty>아직 교과 분석이 없습니다. 담당 교사가 학생부를 확인하고 Work 분석 결과를 반영하면 표시됩니다.</Empty>:<>
    {profile?.analysisContext&&<p className="mb-4 rounded-xl border bg-white p-4 text-sm leading-6">분석 기준일 {profile.analysisContext.asOf||"미확인"} · {profile.analysisContext.curriculum||"교육과정 확인 필요"} · {gradingSystems[profile.analysisContext.gradingSystem as keyof typeof gradingSystems]||"성적 체계 확인 필요"}</p>}
    <Tabs defaultValue="chart"><TabsList className="mb-5 h-auto flex-wrap"><TabsTrigger value="chart">성적 추이</TabsTrigger><TabsTrigger value="courses">과목·성적</TabsTrigger><TabsTrigger value="credits">실제 학점</TabsTrigger><TabsTrigger value="trends">변화와 근거</TabsTrigger></TabsList>
      <TabsContent value="chart">{profile&&<AcademicTrendChart key={`${id}:${profile.id}`} data={data} studentId={id} snapshotId={profile.id}/>}</TabsContent>
      <TabsContent value="courses"><Card><CardContent className="p-0"><div className="overflow-x-auto"><Table><TableHeader><TableRow>{["시기","교과·과목","상태","학점","원점수","성취도","등급·체계","평균·인원","근거"].map(t=><TableHead key={t}>{t}</TableHead>)}</TableRow></TableHeader><TableBody>{courses.map(c=><TableRow key={c.id}><TableCell>{c.schoolYear}<br/>{c.gradeLevel}-{c.semester}</TableCell><TableCell><p className="font-semibold">{c.subject}</p><p className="text-sm text-[#718095]">{c.subjectGroup} · {c.courseType}</p></TableCell><TableCell><Badge variant="outline">{status[c.selectionStatus]}</Badge></TableCell><TableCell>{c.credits??"미확인"}</TableCell><TableCell>{c.rawScore||"—"}</TableCell><TableCell>{c.achievement||"—"}</TableCell><TableCell>{c.rankGrade||"—"}<p className="text-sm text-[#718095]">{gradingSystems[c.gradingSystem??"unknown"]}</p></TableCell><TableCell>{c.classAverage||"—"} / {c.studentCount??"—"}명</TableCell><TableCell><EvidenceButton data={data} studentId={id} snapshotId={c.snapshotId} refs={c.evidenceRefs??[]}/>{c.evidenceText&&<details className="mt-2 max-w-72"><summary className="cursor-pointer text-sm">추출 근거 문장</summary><p className="whitespace-normal text-sm leading-6">{c.evidenceText}</p></details>}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="credits"><p className="mb-4 text-sm leading-6 text-[#65768b]">같은 학년도·학기·과목은 한 번만 계산합니다. 학점·상태가 충돌하는 기록은 합산에서 제외하고 확인 대상으로 표시합니다.</p><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{groups.map(g=><Card key={g.subjectGroup}><CardContent className="space-y-4 p-5"><h2 className="font-semibold">{g.subjectGroup}</h2><div><p className="text-sm text-[#65768b]">확인된 이수 학점</p><p className="text-3xl font-bold">{g.completed}<span className="ml-2 text-sm font-normal">학점</span></p></div><div className="grid grid-cols-2 gap-3 text-sm"><p className="rounded-lg bg-blue-50 p-3">선택·수강 {g.selected}학점</p><p className="rounded-lg bg-slate-50 p-3">향후 계획 {g.planned}학점</p></div>{(g.unknown>0||g.conflicts>0)&&<p className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">학점 미확인 {g.unknown}개 · 중복 충돌 {g.conflicts}개. 표시 합계는 확인 가능한 기록만 포함합니다.</p>}{g.duplicates>0&&<p className="text-sm text-[#65768b]">반복된 동일 과목 {g.duplicates}개를 중복 합산하지 않았습니다.</p>}</CardContent></Card>)}</div>{summaries.length>0&&<details className="mt-4 rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">Work가 작성한 학점 요약과 대조</summary><p className="mt-2 text-sm text-[#65768b]">기존 형식의 0과 미확인 값은 확정 이수로 해석하지 않습니다.</p>{summaries.map(s=><div key={s.id} className="mt-3 border-t pt-3 text-sm leading-6"><p>{s.subjectGroup}: 이수 {s.completedCredits??"미확인"} / 선택 {s.selectedCredits??"미확인"} / 계획 {s.plannedCredits??"미확인"}</p><p>{s.note}</p></div>)}</details>}</TabsContent>
      <TabsContent value="trends"><div className="space-y-4">{trends.length?trends.map(t=>{const matches=courses.filter(c=>c.subjectGroup===t.subjectGroup&&(!t.subject||c.subject===t.subject)),systems=new Set(matches.map(c=>c.gradingSystem??"unknown"));const comparable=!!t.subject&&systems.size===1&&!systems.has("unknown");return <Card key={t.id}><CardContent className="space-y-3 p-5"><div className="flex flex-wrap gap-2"><h2 className="font-semibold">{t.subject||t.subjectGroup}</h2><Badge variant="outline">{comparable?({up:"상승 해석",down:"하락 해석",steady:"유지 해석",mixed:"혼합",insufficient:"자료 부족"}[t.direction]):"비교 조건 확인 필요"}</Badge></div>{!comparable&&<p className="rounded-xl bg-amber-50 p-3 text-sm leading-6 text-amber-900">과목과 평가 체계가 같다고 확인되지 않았습니다. 숫자만으로 상승·하락을 확정하지 않습니다.</p>}<div className="flex flex-wrap gap-2">{t.points.map((point,i)=><p key={i} className="rounded-xl bg-[#f4f7fb] p-3 text-sm">{point.label} · {point.value}</p>)}</div><p className="text-base leading-7">{t.summary}</p><EvidenceButton data={data} studentId={id} snapshotId={t.snapshotId} refs={t.evidenceRefs}/></CardContent></Card>;}):<Empty>변화 해석이 아직 없습니다. 과목별 원자료를 먼저 확인하세요.</Empty>}</div></TabsContent>
    </Tabs></>}</>;
}

export function FingerprintView(p:Props&{staff:boolean;busy:boolean;onActivate:(id:number)=>Promise<void>}){
  const id=selectedId(p),{data}=p,profile=data.profileSnapshots.find(s=>s.studentId===id&&s.isActive),versions=data.profileSnapshots.filter(s=>s.studentId===id),keywords=data.researchKeywords.filter(k=>k.studentId===id),sections=data.profileSections.filter(s=>s.studentId===id);
  return <><Top p={p} title="연구지문과 질문의 연결" description="키워드의 비중은 활동의 우열이나 합격 가능성을 뜻하지 않습니다. 연결 이유와 원문을 확인하세요."/>{!profile?<Empty>아직 반영된 분석 결과가 없습니다. 원본만 업로드하면 분석이 자동 실행되지는 않습니다.</Empty>:<div className="space-y-5"><Card><CardContent className="space-y-4 p-5"><Badge variant="outline">{profile.versionLabel} · {profile.sourceYears.join("·")}학년도</Badge><h2 className="text-xl font-semibold">{profile.oneLineProfile}</h2><p className="whitespace-pre-wrap text-base leading-7">{profile.narrative}</p>{profile.cautions.length>0&&<details><summary className="cursor-pointer font-semibold text-amber-900">판단의 한계와 확인할 자료</summary><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-6">{profile.cautions.map((c,i)=><li key={i}>{c}</li>)}</ul></details>}</CardContent></Card>
    <VersionComparison key={id} versions={versions} busy={p.busy} staff={p.staff} onActivate={p.onActivate}/>
    <div className="grid items-start gap-5 xl:grid-cols-[.7fr_1.3fr]"><Card><CardContent className="space-y-5 p-5"><h2 className="text-lg font-semibold">주요 키워드</h2>{keywords.map(k=><div key={k.id} className="space-y-2"><div className="flex justify-between gap-2"><p className="font-semibold">{k.keyword}</p><span className="text-sm text-[#65768b]">{k.category}</span></div><Progress value={k.weight} className="h-2"/><p className="text-sm leading-6 text-[#65768b]">{k.description}</p><EvidenceButton data={data} studentId={id} snapshotId={k.snapshotId} refs={k.evidenceRefs}/></div>)}</CardContent></Card><Card><CardContent className="p-5"><ResearchNetwork key={id} data={data} studentId={id}/></CardContent></Card></div>
    <section className="space-y-4"><h2 className="text-lg font-semibold">학생부 근거 카드</h2><div className="grid gap-4 lg:grid-cols-2">{sections.map(s=><SourceCard key={s.id} section={s} data={data}/>)}</div></section></div>}</>;
}
function ResearchNetwork({data,studentId}:{data:PortalData;studentId:number}){
  const nodes=data.ontologyNodes.filter(n=>n.studentId===studentId),edges=data.ontologyEdges.filter(e=>e.studentId===studentId);
  const [query,setQuery]=React.useState(""),[focus,setFocus]=React.useState(nodes[0]?.nodeKey??"");const marker=React.useId().replace(/[^a-zA-Z0-9]/g,"");
  const node=nodes.find(n=>n.nodeKey===focus)??nodes[0],filtered=nodes.filter(n=>`${n.label} ${n.description} ${n.nodeType}`.toLowerCase().includes(query.toLowerCase()));
  if(!node)return <Empty>아직 연결된 개념·질문이 없습니다.</Empty>;
  const linked=edges.filter(e=>e.sourceKey===node.nodeKey||e.targetKey===node.nodeKey),neighbors=nodes.filter(n=>linked.some(e=>e.sourceKey===n.nodeKey||e.targetKey===n.nodeKey)&&n.nodeKey!==node.nodeKey);
  const visible=[node,...neighbors.slice(0,12)],positions=new Map<string,{x:number;y:number}>();positions.set(node.nodeKey,{x:300,y:230});
  visible.slice(1).forEach((n,i)=>{const angle=i/Math.max(visible.length-1,1)*Math.PI*2-Math.PI/2;positions.set(n.nodeKey,{x:300+Math.cos(angle)*218,y:230+Math.sin(angle)*164});});
  return <div className="space-y-4"><h2 className="text-lg font-semibold">개념·활동·질문 탐색</h2><Input aria-label="연결망 노드 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder={`${nodes.length}개 노드에서 검색`}/><Choice label="확인할 노드" value={node.nodeKey} onChange={setFocus} items={filtered.some(n=>n.nodeKey===node.nodeKey)?filtered.map(n=>[n.nodeKey,n.label]):[[node.nodeKey,node.label],...filtered.map(n=>[n.nodeKey,n.label] as [string,string])]}/>
    <svg viewBox="0 0 600 460" className="w-full rounded-xl bg-[#f6f9fd]" role="group" aria-label="선택한 노드와 이웃 연결"><defs><marker id={marker} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#859ebf"/></marker></defs>{linked.filter(e=>positions.has(e.sourceKey)&&positions.has(e.targetKey)).map(e=>{const a=positions.get(e.sourceKey)!,b=positions.get(e.targetKey)!,d=Math.hypot(b.x-a.x,b.y-a.y)||1;return <line key={e.id} x1={a.x+(b.x-a.x)*38/d} y1={a.y+(b.y-a.y)*38/d} x2={b.x-(b.x-a.x)*43/d} y2={b.y-(b.y-a.y)*43/d} stroke="#aac0dc" strokeWidth={1.5} markerEnd={`url(#${marker})`}/>;})}{visible.map(n=>{const point=positions.get(n.nodeKey)!,main=n.nodeKey===node.nodeKey;return <g key={n.nodeKey} role="button" tabIndex={0} aria-label={`${n.label} 연결 보기`} className="cursor-pointer" onClick={()=>setFocus(n.nodeKey)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setFocus(n.nodeKey);}}}><title>{n.label}</title><circle cx={point.x} cy={point.y} r={main?46:34} fill={main?"#173a73":"#e0eaf8"} stroke="#829dbf"/><text x={point.x} y={point.y+4} textAnchor="middle" fill={main?"white":"#173a73"} fontSize="12" fontWeight="600">{n.label.length>9?n.label.slice(0,9)+"…":n.label}</text></g>;})}</svg>
    {neighbors.length>12&&<p className="text-sm text-[#65768b]">그림에는 이웃 12개를 표시합니다. 아래 목록에서 전체 {linked.length}개 연결을 확인할 수 있습니다.</p>}
    <div className="space-y-3 rounded-xl border p-4"><h3 className="font-semibold">{node.label}</h3><p className="text-sm leading-6">{node.description}</p><EvidenceButton data={data} studentId={studentId} snapshotId={node.snapshotId} refs={node.evidenceRefs}/></div>
    <div className="max-h-96 space-y-3 overflow-y-auto">{linked.map(e=>{const other=nodes.find(n=>n.nodeKey===(e.sourceKey===node.nodeKey?e.targetKey:e.sourceKey));return <div key={e.id} className="space-y-2 rounded-xl border p-3"><Button variant="ghost" className="h-auto justify-start whitespace-normal px-0 text-left" onClick={()=>other&&setFocus(other.nodeKey)}>{e.sourceKey===node.nodeKey?node.label:other?.label}<ArrowRight className="shrink-0"/>{e.targetKey===node.nodeKey?node.label:other?.label}</Button><p className="text-sm font-semibold">{e.relation} · {e.sourceState==="recorded"?"기록된 연결":"분석에서 제안한 연결"}</p><p className="text-sm leading-6">{e.description}</p><EvidenceButton data={data} studentId={studentId} snapshotId={e.snapshotId} refs={e.evidenceRefs??[]} label="연결의 근거"/></div>;})}{!linked.length&&<p className="text-sm text-[#65768b]">연결이 아직 없습니다. 개별 노드의 근거를 확인하세요.</p>}</div>
  </div>;
}
type Comparison={before:{versionLabel:string;narrative:string};after:{versionLabel:string;narrative:string};difference:ReturnType<typeof profileDifference>};
function VersionComparison({versions,staff,busy,onActivate}:{versions:ProfileSnapshot[];staff:boolean;busy:boolean;onActivate:(id:number)=>Promise<void>}){
  const [before,setBefore]=React.useState(String(versions[1]?.id??"none")),[after,setAfter]=React.useState(String(versions[0]?.id??"none")),[comparison,setComparison]=React.useState<Comparison|null>(null),[loading,setLoading]=React.useState(false),[error,setError]=React.useState("");
  const compare=async()=>{setLoading(true);setError("");try{const r=await fetch(`/api/profile-comparison?before=${before}&after=${after}`);const body=await r.json() as Comparison&{error?:string};if(!r.ok)throw new Error(body.error);setComparison(body);}catch(e){setError(e instanceof Error?e.message:"비교하지 못했습니다.");}finally{setLoading(false);}};
  return <Card><CardContent className="space-y-4 p-5"><h2 className="text-lg font-semibold">분석 버전과 변경 비교</h2><div className="flex flex-wrap gap-3">{versions.map(v=><div key={v.id} className="rounded-xl border p-3 text-sm"><p className="font-semibold">{v.versionLabel} {v.isActive&&<Badge variant="outline">활성</Badge>}</p><p className="mt-1 text-[#65768b]">{new Date(v.createdAt).toLocaleDateString("ko-KR")}</p>{staff&&!v.isActive&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>void onActivate(v.id)} className="mt-2">이 버전 활성화</Button>}</div>)}</div>{versions.length>1&&<div className="grid gap-3 sm:grid-cols-[1fr_1fr_auto]"><Choice label="이전 분석" value={before} onChange={setBefore} items={versions.map(v=>[String(v.id),v.versionLabel])}/><Choice label="이후 분석" value={after} onChange={setAfter} items={versions.map(v=>[String(v.id),v.versionLabel])}/><Button variant="outline" disabled={loading||before===after||before==="none"} onClick={()=>void compare()}><History/>{loading?"비교 중…":"차이 확인"}</Button></div>}{error&&<p role="alert" className="text-sm text-rose-800">{error}</p>}
    {comparison&&<div className="space-y-4 border-t pt-4"><p className="text-sm leading-6 text-[#65768b]">같은 항목 ID를 기준으로 비교합니다. 표현이 바뀐 사실만으로 학생의 성장을 판단하지 않습니다.</p><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["새 근거 항목",comparison.difference.added],["빠진 항목",comparison.difference.removed],["근거·출처 변경",comparison.difference.evidenceChanged],["같은 근거의 설명 변경",comparison.difference.wordingChanged]].map(([label,rows])=><div key={String(label)} className="rounded-xl bg-[#f5f8fc] p-3"><p className="text-sm font-semibold">{String(label)} · {(rows as Array<unknown>).length}</p><ul className="mt-2 list-disc pl-4 text-sm leading-6">{(rows as Array<{id:string;title:string}>).map(r=><li key={r.id}>{r.title}</li>)}</ul></div>)}</div><p className="text-sm">교과 기록 {comparison.difference.academicChanged?"변경됨":"동일"} · 적용 기준 {comparison.difference.criteriaChanged?"변경됨":"동일"}</p><div className="grid gap-4 md:grid-cols-2">{[comparison.before,comparison.after].map((v,i)=><div key={i} className="rounded-xl border p-4"><h3 className="font-semibold">{v.versionLabel}</h3><p className="mt-3 whitespace-pre-wrap text-sm leading-6">{v.narrative}</p></div>)}</div></div>}
  </CardContent></Card>;
}

export function EvaluationView(p:Props){
  const id=selectedId(p),{data}=p,references=data.evaluationReferences.filter(r=>r.studentId===id);const [selected,setSelected]=React.useState("");const active=references.find(r=>r.sourceKey===selected)??references[0],evaluations=data.competencyEvaluations.filter(e=>e.studentId===id&&e.sourceKey===active?.sourceKey),checks=data.referenceChecks.filter(c=>c.studentId===id&&c.sourceKey===active?.sourceKey);
  return <><Top p={p} title="역량의 근거와 다음 점검" description="적용한 대학·전형·학년도별로 확인된 근거와 추가로 확인할 자료를 보여줍니다."/>{!active?<Empty>적용된 평가 자료가 없습니다. 관리자 자료실의 기준을 실제로 읽고 작성한 Work 결과가 필요합니다.</Empty>:<div className="space-y-5"><Choice label="적용 평가 자료" value={active.sourceKey} onChange={setSelected} items={references.map(r=>[r.sourceKey,`${r.institution} ${r.admissionsYear??""} · ${r.title}`])}/><Card><CardContent className="space-y-2 p-5"><h2 className="font-semibold">{active.title}</h2><p className="text-sm">{active.institution} · {active.admissionsYear?`${active.admissionsYear}학년도`:"학년도 확인 필요"} · {active.admissionTrack} · {active.department||"모집단위 확인 필요"}</p>{active.note&&<p className="text-sm leading-6 text-[#65768b]">{active.note}</p>}</CardContent></Card>{checks.map((c,i)=><div key={i} role="status" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900"><p className="font-semibold">기준 재점검 필요</p>{c.reasons.map((reason,j)=><p key={j}>{reason}</p>)}</div>)}<div className="grid gap-4 lg:grid-cols-2">{evaluations.map(e=><CompetencyCard key={e.id} item={e} data={data}/>)}</div></div>}</>;
}
function CompetencyCard({item,data}:{item:CompetencyEvaluation;data:PortalData}){
  const labels={documented:"근거 연결됨",partial:"일부 근거·추가 확인",missing:"자료 확인 필요",not_applicable:"해당 없음"};
  return <Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-lg font-semibold">{item.competency}</h2><Badge variant="outline">{labels[item.evidenceState??"partial"]}</Badge></div><p className="text-base leading-7">{item.summary}</p><EvidenceButton data={data} studentId={item.studentId} snapshotId={item.snapshotId} refs={item.evidenceRefs}/><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-emerald-50 p-3"><h3 className="text-sm font-semibold">근거에서 확인할 강점</h3><ul className="mt-2 list-disc space-y-2 pl-4 text-sm leading-6">{item.strengths.map((v,i)=><li key={i}>{v}</li>)}</ul></div><div className="rounded-xl bg-amber-50 p-3"><h3 className="text-sm font-semibold">추가 확인할 자료</h3><ul className="mt-2 list-disc space-y-2 pl-4 text-sm leading-6">{item.gaps.map((v,i)=><li key={i}>{v}</li>)}</ul></div></div>{item.nextActions.length>0&&<div className="rounded-xl border p-3"><h3 className="text-sm font-semibold">다음 행동 후보</h3><ul className="mt-2 list-disc space-y-2 pl-4 text-sm leading-6">{item.nextActions.slice(0,3).map((v,i)=><li key={i}>{v}</li>)}</ul><p className="mt-2 text-sm text-[#65768b]">필요한 한 가지를 골라 ‘다음 행동·피드백’에 기록하세요.</p></div>}{item.scoreMethod&&item.score!==null&&<details className="text-sm leading-6"><summary className="cursor-pointer">출처 척도 적용값 {item.score} / {item.scoreMethod.maximum}</summary><p>{item.scoreMethod.rubric} · 기준 자료 {item.scoreMethod.sourcePage}쪽</p><p>분석 보조값입니다. 대학의 실제 평가 결과나 합격 확률이 아닙니다.</p></details>}{item.caveat&&<p className="rounded-lg bg-slate-50 p-3 text-sm leading-6 text-[#65768b]">{item.caveat}</p>}</CardContent></Card>;
}

export function WikiView(p:Props){
  const id=selectedId(p),{data}=p,pages=data.wikiPages.filter(w=>w.studentId===id),nodes=data.ontologyNodes.filter(n=>n.studentId===id);
  const [pageId,setPageId]=React.useState<number|null>(null),[query,setQuery]=React.useState(""),[nodeKey,setNodeKey]=React.useState<string|null>(null);
  const page=pages.find(w=>w.id===pageId)??pages[0],node=nodes.find(n=>n.nodeKey===nodeKey);
  const open=(target:string)=>{let key=target.replace(/^wiki:|^#|\.md$/g,"");try{key=decodeURIComponent(key);}catch{}const next=pages.find(w=>w.slug===key||w.title===key);if(next){setPageId(next.id);return;}const linked=nodes.find(n=>n.nodeKey===target.replace(/^node:/,""));if(linked){setNodeKey(linked.nodeKey);return;}toast.message("이 분석 버전에 연결된 문서를 찾지 못했습니다.");};
  return <><Top p={p} title="근거를 연결한 학생 위키" description="개념·질문·활동을 오가며 내 탐구를 설명합니다. 원문 근거와 아직 확인하지 못한 내용을 함께 봅니다."/>{!page?<Empty>위키 분석 결과가 아직 없습니다.</Empty>:<div className="grid gap-5 lg:grid-cols-[270px_1fr]"><aside className="h-fit rounded-xl border bg-white p-4"><Input aria-label="학생 위키 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="문서·개념 검색"/><nav aria-label="학생 위키 문서" className="mt-3 space-y-2">{pages.filter(w=>`${w.title} ${w.summary} ${w.keywords.join(" ")}`.toLowerCase().includes(query.toLowerCase())).map(w=><button key={w.id} onClick={()=>setPageId(w.id)} className={`w-full rounded-xl p-3 text-left ${w.id===page.id?"bg-[#173a73] text-white":"bg-[#f6f8fc]"}`}><p className="text-sm font-semibold">{w.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 opacity-75">{w.summary}</p></button>)}</nav></aside><article className="trace-print-target space-y-5 rounded-2xl border bg-white p-5 sm:p-8"><div className="flex flex-wrap justify-between gap-3"><div className="flex flex-wrap gap-2">{page.keywords.map(k=><Badge key={k} variant="outline">{k}</Badge>)}</div><Button size="sm" variant="outline" className="print:hidden" onClick={()=>window.print()}><Printer/>인쇄·PDF 저장</Button></div><h2 className="text-3xl font-bold">{page.title}</h2><p className="border-l-4 border-[#77d9bd] pl-4 text-base leading-7 text-[#65768b]">{page.summary}</p><LinkedMarkdown value={page.bodyMarkdown} onInternal={open}/><section className="space-y-3 border-t pt-5"><h3 className="font-semibold">연결된 개념·질문</h3><div className="flex flex-wrap gap-2">{page.linkedNodeKeys.map(key=><Button key={key} variant="outline" size="sm" onClick={()=>setNodeKey(key)}>{nodes.find(n=>n.nodeKey===key)?.label??key}</Button>)}</div></section><section className="space-y-3 border-t pt-5"><h3 className="font-semibold">같은 근거를 이어 읽기</h3>{pages.filter(w=>w.id!==page.id&&w.linkedNodeKeys.some(k=>page.linkedNodeKeys.includes(k))).map(w=><Button key={w.id} variant="ghost" className="h-auto whitespace-normal text-left" onClick={()=>setPageId(w.id)}>{w.title}<ArrowRight/></Button>)}</section></article></div>}
    <Dialog open={Boolean(nodeKey)} onOpenChange={v=>{if(!v)setNodeKey(null);}}><DialogContent className="max-h-[85vh] overflow-y-auto"><DialogHeader><DialogTitle>{node?.label??"연결 확인"}</DialogTitle><DialogDescription>{node?.description??"이 버전에서 연결 노드를 찾지 못했습니다."}</DialogDescription></DialogHeader>{node&&<EvidenceButton data={data} studentId={id} snapshotId={node.snapshotId} refs={node.evidenceRefs}/>}<div className="space-y-2">{pages.filter(w=>w.linkedNodeKeys.includes(nodeKey??"")).map(w=><Button key={w.id} variant="outline" className="h-auto w-full justify-start whitespace-normal text-left" onClick={()=>{setPageId(w.id);setNodeKey(null);}}>{w.title}</Button>)}</div></DialogContent></Dialog>
  </>;
}
