"use client";

import { clientId } from "@/lib/client-id";
import * as React from "react";
import { Plus, History, MessageSquare, CheckCircle2, ArrowRight, FileText } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card,CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Select,SelectContent,SelectItem,SelectTrigger,SelectValue } from "@/components/ui/select";
import { Dialog,DialogContent,DialogDescription,DialogFooter,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Tabs,TabsList,TabsTrigger,TabsContent } from "@/components/ui/tabs";
import type { PortalData,Student } from "@/lib/portal-types";
import { guidanceKinds,guidanceStatuses,guidancePayloadSchema,questionOrigins,questionPerspectives,workKinds,type GuidanceEntry,type GuidanceKind,type GuidancePayload } from "@/lib/guidance";

export type GuidanceSave=(body:Record<string,unknown>)=>Promise<void>;
export function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="grid gap-2"><Label>{label}</Label>{children}</div>;}
export function Choice({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:Array<[string,string]>;label:string}){return <Select value={value} onValueChange={v=>{if(v!==null)onChange(v);}}><SelectTrigger aria-label={label} className="w-full"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>;}

export function GuidanceView({data,students,selectedStudentId,onSelect,onSave,busy,initialEntryKey}:{data:PortalData;students:Student[];selectedStudentId:number|null;onSelect:(id:number)=>void;onSave:GuidanceSave;busy:boolean;initialEntryKey?:string}){
  const staff=data.viewer.role!=="student";const selected=students.find(s=>s.id===selectedStudentId)??students[0];
  const initialEntry=data.guidance.find(e=>e.entityKey===initialEntryKey&&e.studentId===selected?.id);
  const [focusKey,setFocusKey]=React.useState(initialEntry?.entityKey);
  const [tab,setTab]=React.useState(initialEntry?.kind==="question"?"questions":initialEntry&&["observation","record_review"].includes(initialEntry.kind)?"observations":"work"),[filter,setFilter]=React.useState("all");
  const [editor,setEditor]=React.useState<{entry?:GuidanceEntry;kind:GuidanceKind;parent?:GuidanceEntry}|null>(null);
  const [reply,setReply]=React.useState<{entry:GuidanceEntry;review:boolean}|null>(null);
  const [history,setHistory]=React.useState<GuidanceEntry[]|null>(null),[historyBusy,setHistoryBusy]=React.useState(false);
  const own=data.guidance.filter(e=>e.studentId===selected?.id&&workKinds.includes(e.kind));
  const classIds=new Set(students.map(s=>s.id));
  const awaiting=data.guidance.filter(e=>e.studentId&&classIds.has(e.studentId)&&e.payload.status==="submitted");
  const corrections=data.guidance.filter(e=>e.studentId&&classIds.has(e.studentId)&&e.kind==="correction"&&!["confirmed","closed"].includes(e.payload.status));
  const checks=data.referenceChecks.filter(c=>classIds.has(c.studentId));
  const newEntry=(kind:GuidanceKind,parent?:GuidanceEntry)=>{if(selected)setEditor({kind,parent});};
  const showHistory=async(entry:GuidanceEntry)=>{setHistoryBusy(true);try{const response=await fetch(`/api/guidance?key=${encodeURIComponent(entry.entityKey)}`);const body=await response.json() as {error?:string;history:GuidanceEntry[]};if(!response.ok)throw new Error(body.error);setHistory(body.history);}catch(e){toast.error(e instanceof Error?e.message:"이력을 읽지 못했습니다.");}finally{setHistoryBusy(false);}};
  const list=own.filter(e=>!focusKey||e.entityKey===focusKey).filter(e=>tab==="questions"?e.kind==="question":tab==="observations"?["observation","record_review"].includes(e.kind):e.kind!=="question"&&!["observation","record_review"].includes(e.kind)).filter(e=>filter==="all"||e.payload.status===filter).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)||b.id-a.id);
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">{staff?"지도와 피드백":"나의 다음 행동"}</h1><p className="mt-3 text-base leading-7 text-[#65768b]">질문 하나, 실행한 근거, 피드백 뒤 달라진 점을 이어서 남깁니다.</p></div>{selected&&<div className="w-full sm:w-64"><Choice label="학생 선택" value={String(selected.id)} onChange={v=>{onSelect(Number(v));setEditor(null);setReply(null);}} items={students.map(s=>[String(s.id),`${s.name} · ${s.studentNumber}`])}/></div>}</div>
    {staff&&<div className="grid gap-3 sm:grid-cols-3">{[["피드백 확인 대기",awaiting.length],["분석 정정 요청",corrections.length],["기준 재점검",checks.length]].map(([label,count])=><Card key={label}><CardContent className="p-4"><p className="text-sm text-[#65768b]">{label}</p><p className="mt-2 text-2xl font-bold">{count}건</p></CardContent></Card>)}</div>}
    {staff&&(awaiting.length>0||checks.length>0)&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-semibold">현재 학급에서 확인할 학생</summary><div className="mt-3 space-y-2">{awaiting.slice(0,30).map(e=><button key={e.entityKey} className="flex w-full items-center gap-2 rounded-lg bg-[#f4f7fb] p-3 text-left text-sm" onClick={()=>{onSelect(e.studentId!);setTab(e.kind==="question"?"questions":e.kind==="observation"||e.kind==="record_review"?"observations":"work");setFilter("all");}}>{students.find(s=>s.id===e.studentId)?.name} · {e.payload.title}<ArrowRight className="ml-auto size-4"/></button>)}{checks.map((c,i)=><p key={i} className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">{students.find(s=>s.id===c.studentId)?.name} · {c.title}: {c.reasons.join(" ")}</p>)}</div></details>}
    {!selected?<p className="rounded-xl border bg-white p-6">등록된 학생이 없습니다.</p>:<>
      <div className="flex flex-wrap gap-2"><Button onClick={()=>newEntry("action")}><Plus/>다음 할 일</Button><Button variant="outline" onClick={()=>newEntry("question")}><Plus/>질문 남기기</Button><Button variant="outline" onClick={()=>newEntry("reflection")}><Plus/>읽기·설명 기록</Button><Button variant="outline" onClick={()=>newEntry("correction")}>정정 요청</Button>{staff&&<><Button variant="outline" onClick={()=>newEntry("observation")}>관찰 기록</Button><Button variant="outline" onClick={()=>newEntry("record_review")}>학생부 검토</Button></>}</div>
      {focusKey&&<div className="flex flex-wrap items-center gap-3 rounded-xl bg-emerald-50 p-4 text-sm"><span>상담 목록에서 선택한 기록입니다.</span><Button size="sm" variant="outline" onClick={()=>setFocusKey(undefined)}>이 학생의 전체 기록 보기</Button></div>}
      <Tabs value={tab} onValueChange={v=>{setTab(v);setFocusKey(undefined);}}><div className="flex flex-wrap justify-between gap-3"><TabsList><TabsTrigger value="work">다음 행동·성찰</TabsTrigger><TabsTrigger value="questions">질문 성장</TabsTrigger><TabsTrigger value="observations">{staff?"관찰·기재 검토":"선생님이 공유한 기록"}</TabsTrigger></TabsList><div className="w-44"><Choice label="처리 상태" value={filter} onChange={setFilter} items={[["all","모든 상태"],...Object.entries(guidanceStatuses)]}/></div></div>
      {["work","questions","observations"].map(value=><TabsContent key={value} value={value} className="mt-5 space-y-4">{value==="questions"&&<p className="rounded-xl bg-[#edf3ff] p-4 text-sm leading-6">일상·교과·기존 활동에서 출발합니다. 처음 질문과 범위를 바꾼 이유를 남기고, 다음 질문이 생기면 이전 질문에서 연결하세요. 모든 관점을 작성할 필요는 없습니다.</p>}{!list.length&&<p className="rounded-xl border bg-white p-6 text-[#65768b]">이 조건에 해당하는 기록이 없습니다. 위에서 질문이나 다음 할 일 하나를 추가하세요.</p>}{list.map(e=>{
        const p=e.payload,parent=own.find(r=>r.entityKey===p.parentKey);const canEdit=staff||p.ownerId===data.viewer.id;const closed=["confirmed","closed"].includes(p.status);
        return <Card key={e.entityKey}><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="mb-2 flex flex-wrap gap-2"><Badge variant="outline">{guidanceKinds[e.kind]}</Badge><Badge variant="secondary">{guidanceStatuses[p.status]}</Badge>{e.audience==="staff"&&<Badge variant="outline">교직원만</Badge>}{p.subject&&<Badge variant="outline">{p.subject}</Badge>}</div><h2 className="text-lg font-bold">{p.title}</h2></div>{p.dueDate&&<span className="text-sm">확인일 {p.dueDate}</span>}</div>
          {parent&&<p className="border-l-4 border-[#c6d6ee] pl-3 text-sm text-[#596d85]">이전 질문·활동: {parent.payload.title}</p>}{p.originalQuestion&&<p className="text-sm leading-6"><span className="font-semibold">처음 질문: </span>{p.originalQuestion}</p>}
          <p className="whitespace-pre-wrap text-base leading-7">{p.text}</p>
          {(p.method||p.result||p.remainingQuestion)&&<div className="grid gap-3 md:grid-cols-3">{[["사용한 방법·자료",p.method],["설명이 바뀐 부분",p.result],["남은 질문",p.remainingQuestion]].filter(([,v])=>v).map(([label,value])=><div key={label} className="rounded-xl bg-[#f5f8fc] p-3"><p className="text-sm font-semibold">{label}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{value}</p></div>)}</div>}
          {(p.sourceNote||p.recordId)&&<div className="rounded-xl border p-3 text-sm leading-6"><p className="font-semibold">연결 근거</p><p className="whitespace-pre-wrap">{p.sourceNote}</p>{p.recordId&&<a className="text-[#2457d6] underline" href={`/api/student-records/${p.recordId}?inline=1${p.page?`#page=${p.page}`:""}`} target="_blank" rel="noreferrer">원문 {p.page?`${p.page}쪽`: "열기"}</a>}{p.sourceUrl&&<a className="ml-3 text-[#2457d6] underline" href={p.sourceUrl} target="_blank" rel="noreferrer">자료 출처</a>}</div>}
          {(p.achievementStandard||p.learningRoutine||p.contribution||p.observationInterpretation)&&<details className="rounded-xl border p-3"><summary className="cursor-pointer text-sm font-semibold">학습 과정·기여·관찰 해석</summary><div className="mt-3 space-y-3">{[["성취기준·개념",p.achievementStandard],["학습 루틴",p.learningRoutine],["기여한 행동",p.contribution],["교사 해석",p.observationInterpretation]].filter(([,v])=>v).map(([label,value])=><p key={label} className="whitespace-pre-wrap text-sm leading-6"><span className="font-semibold">{label}: </span>{value}</p>)}</div></details>}
          {p.response&&<div className="rounded-xl bg-[#edf3ff] p-4"><p className="text-sm font-semibold">제출한 실행 결과·설명</p><p className="mt-2 whitespace-pre-wrap text-base leading-7">{p.response}</p></div>}
          {p.feedback&&<div className="rounded-xl bg-[#edf7f3] p-4"><p className="text-sm font-semibold">교사 피드백 {p.reviewedBy&&`· ${p.reviewedBy}`}</p><p className="mt-2 whitespace-pre-wrap text-base leading-7">{p.feedback}</p></div>}
          {e.kind==="correction"&&p.status==="confirmed"&&<p className="text-sm text-[#65768b]">요청 검토 기록입니다. 확정 분석 내용은 담당 교사가 새 Work 결과를 반영한 뒤 바뀝니다.</p>}
          <div className="flex flex-wrap gap-2">{canEdit&&!closed&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setEditor({entry:e,kind:e.kind})}>내용·임시저장 수정</Button>}{!closed&&!["observation","record_review"].includes(e.kind)&&<Button size="sm" disabled={busy} onClick={()=>setReply({entry:e,review:false})}><MessageSquare/>실행 결과 제출</Button>}{staff&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setReply({entry:e,review:true})}><CheckCircle2/>확인·피드백</Button>}{e.kind==="question"&&<Button size="sm" variant="outline" onClick={()=>newEntry("question",e)}>다음 질문 연결</Button>}<Button size="sm" variant="ghost" disabled={historyBusy} onClick={()=>void showHistory(e)}><History/>수정 이력</Button></div>
          <p className="text-xs text-[#718095]">{e.actorName} · {new Date(e.createdAt).toLocaleString("ko-KR")} · {e.revision}번째 저장 · Work 포함 {e.includeInWork?"선택됨":"안 함"}</p>
        </CardContent></Card>;
      })}</TabsContent>)}</Tabs>
    </>}
    {editor&&selected&&<GuidanceEditor key={editor.entry?.entityKey??`${editor.kind}:${editor.parent?.entityKey??"new"}`} data={data} student={selected} kind={editor.kind} entry={editor.entry} parent={editor.parent} busy={busy} onClose={()=>setEditor(null)} onSave={onSave}/>}
    {reply&&<ReplyDialog key={reply.entry.entityKey+reply.review} value={reply} busy={busy} onSave={onSave} onClose={()=>setReply(null)}/>}
    <Dialog open={history!==null} onOpenChange={v=>{if(!v)setHistory(null);}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>수정·피드백 이력</DialogTitle><DialogDescription>이전 기록은 덮어쓰지 않고 보존합니다.</DialogDescription></DialogHeader>{history?.map(e=><div key={e.id} className="space-y-2 rounded-xl border p-4"><p className="text-sm font-semibold">{e.revision}번째 · {e.actorName} · {guidanceStatuses[e.payload.status]}</p><p className="font-semibold">{e.payload.title}</p><p className="whitespace-pre-wrap text-sm leading-6">{e.payload.text}</p>{e.payload.response&&<p className="whitespace-pre-wrap rounded-lg bg-blue-50 p-3 text-sm">제출: {e.payload.response}</p>}{e.payload.feedback&&<p className="whitespace-pre-wrap rounded-lg bg-emerald-50 p-3 text-sm">피드백: {e.payload.feedback}</p>}</div>)}</DialogContent></Dialog>
  </div>;
}

function GuidanceEditor({data,student,kind,entry,parent,busy,onSave,onClose}:{data:PortalData;student:Student;kind:GuidanceKind;entry?:GuidanceEntry;parent?:GuidanceEntry;busy:boolean;onSave:GuidanceSave;onClose:()=>void}){
  const [payload,setPayload]=React.useState<GuidancePayload>(()=>entry?.payload??guidancePayloadSchema.parse({title:"새 기록",originalQuestion:parent?.payload.title??"",origin:parent?"followup":"daily",parentKey:parent?.entityKey??"",subject:parent?.payload.subject??""}));
  const [title,setTitle]=React.useState(entry?.payload.title??""),[include,setInclude]=React.useState(entry?.includeInWork??false),[privateNote,setPrivateNote]=React.useState(entry?.audience==="staff"),[error,setError]=React.useState("");
  const key=React.useRef(entry?.entityKey??clientId()),staff=data.viewer.role!=="student";
  const put=<K extends keyof GuidancePayload>(name:K,value:GuidancePayload[K])=>setPayload(p=>({...p,[name]:value}));
  const save=async(draft:boolean)=>{setError("");try{await onSave({kind,studentId:student.id,entityKey:key.current,expectedRevision:entry?.revision??0,intent:"save",audience:privateNote?"staff":"student",includeInWork:include,payload:{...payload,title,status:draft?"draft":"active"}});onClose();}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}};
  return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{guidanceKinds[kind]} · {student.name}</DialogTitle><DialogDescription>{kind==="question"?"질문 한 문장부터 시작합니다. 필요한 항목만 펼쳐 작성하세요.":"한 가지 행동과 확인할 근거를 짧게 남깁니다."}</DialogDescription></DialogHeader><div className="grid gap-4">
    <Field label={kind==="question"?"지금 궁금한 질문":"제목"}><Input aria-label="기록 제목" value={title} maxLength={180} onChange={e=>setTitle(e.target.value)} disabled={busy}/></Field>
    {kind==="question"&&<Choice label="질문의 출발" value={payload.origin} onChange={v=>put("origin",v as GuidancePayload["origin"])} items={Object.entries(questionOrigins)}/>}
    <Field label={kind==="correction"?"어떤 내용이 사실과 다릅니까?":kind==="observation"?"직접 관찰한 행동":kind==="record_review"?"검토할 원문과 확인할 쟁점":kind==="question"?"왜 궁금한가요? 이전 질문을 바꿨다면 그 이유":kind==="reflection"?"읽기 전 생각과 읽은 뒤 달라진 설명":"무엇을 해볼 것인가요? 왜 필요한가요?"}><Textarea aria-label="기록 내용" className="min-h-28 text-base" value={payload.text} maxLength={8000} onChange={e=>put("text",e.target.value)} disabled={busy}/></Field>
    <div className="grid gap-4 sm:grid-cols-2"><Field label="연결 교과·활동 · 선택"><Input aria-label="연결 교과" value={payload.subject} maxLength={150} onChange={e=>put("subject",e.target.value)}/></Field><Field label="다시 확인할 날짜 · 선택"><Input aria-label="다시 확인할 날짜" type="date" value={payload.dueDate} onChange={e=>put("dueDate",e.target.value)}/></Field></div>
    {kind==="question"&&<details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">질문을 구체화하는 여섯 관점 · 필요한 것만 선택</summary><div className="mt-3 flex flex-wrap gap-2">{questionPerspectives.map(p=><Button key={p} size="sm" variant={payload.perspective===p?"default":"outline"} onClick={()=>put("perspective",p)}>{p}</Button>)}</div><p className="mt-3 text-sm leading-6 text-[#65768b]">대상·상황·비교 기준·자료 범위 중 한 가지만 좁혀도 됩니다. 선택한 관점에 따라 질문을 고친 이유를 위에 적으세요.</p></details>}
    <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">자료·방법·설명의 변화 · 선택</summary><div className="mt-4 grid gap-4"><Field label="처음 질문"><Textarea aria-label="처음 질문" value={payload.originalQuestion} onChange={e=>put("originalQuestion",e.target.value)}/></Field>{[["method","사용한 방법·읽은 자료"],["result","확인한 내용·달라진 설명"],["remainingQuestion","아직 남은 질문"]].map(([name,label])=><Field key={name} label={label}><Textarea aria-label={label} value={payload[name as "method"|"result"|"remainingQuestion"]} onChange={e=>put(name as "method"|"result"|"remainingQuestion",e.target.value)}/></Field>)}</div></details>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-semibold">교과 성취·학습 루틴·공동체 기여 · 선택</summary><div className="mt-4 grid gap-4">{([["achievementStandard","연결한 성취기준·교과 개념"],["learningRoutine","직접 실천한 학습 방법·루틴"],["contribution","수업·모둠에 기여한 행동"]] as const).map(([key,label])=><Field key={key} label={label}><Textarea aria-label={label} value={payload[key]} onChange={e=>put(key,e.target.value)}/></Field>)}{staff&&<Field label="관찰에 대한 교사의 해석 · 사실과 구분"><Textarea aria-label="교사 관찰 해석" value={payload.observationInterpretation} onChange={e=>put("observationInterpretation",e.target.value)}/></Field>}</div></details>
    <details className="rounded-xl border p-4" open={kind==="correction"||kind==="record_review"}><summary className="cursor-pointer text-sm font-semibold">확인할 근거 연결</summary><div className="mt-4 grid gap-4"><Choice label="원본 연결" value={String(payload.recordId??"none")} onChange={v=>{put("recordId",v==="none"?null:Number(v));if(v==="none")put("page",null);}} items={[["none","원본 위치 미연결"],...data.records.filter(r=>r.studentId===student.id).map(r=>[String(r.id),r.originalName] as [string,string])]}/><Field label="원문 쪽수 · 확인한 경우만"><Input aria-label="원문 쪽수" type="number" min={1} max={10000} value={payload.page??""} disabled={!payload.recordId} onChange={e=>put("page",e.target.value?Number(e.target.value):null)}/></Field><Field label="근거 문장·제출물 위치·출처"><Textarea aria-label="근거 설명" value={payload.sourceNote} onChange={e=>put("sourceNote",e.target.value)}/></Field><Field label="공개 자료 주소 · 선택"><Input aria-label="자료 주소" value={payload.sourceUrl} onChange={e=>put("sourceUrl",e.target.value)} placeholder="https://"/></Field></div></details>
    <label className="flex items-start gap-2 text-sm leading-6"><Checkbox checked={include} onCheckedChange={v=>setInclude(v===true)}/>다음 Work 분석 묶음에 이 기록 포함</label>{staff&&<label className="flex items-start gap-2 text-sm leading-6"><Checkbox checked={privateNote} onCheckedChange={v=>setPrivateNote(v===true)}/>담당 교사·관리자만 열람</label>}
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
  </div><DialogFooter><Button variant="outline" disabled={busy||!title.trim()} onClick={()=>void save(true)}>임시 저장</Button><Button disabled={busy||!title.trim()} onClick={()=>void save(false)}>{busy?"저장 중…":"기록 저장"}</Button></DialogFooter></DialogContent></Dialog>;
}
function ReplyDialog({value,busy,onSave,onClose}:{value:{entry:GuidanceEntry;review:boolean};busy:boolean;onSave:GuidanceSave;onClose:()=>void}){
  const {entry,review}=value;const [text,setText]=React.useState(review?entry.payload.feedback:entry.payload.response),[status,setStatus]=React.useState("confirmed"),[error,setError]=React.useState("");
  const save=async()=>{try{await onSave({kind:entry.kind,studentId:entry.studentId,entityKey:entry.entityKey,expectedRevision:entry.revision,intent:review?"review":"submit",payload:review?{feedback:text,status}:{response:text}});onClose();}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}};
  return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent><DialogHeader><DialogTitle>{review?"교사 확인과 피드백":"실행 결과 제출"}</DialogTitle><DialogDescription>{entry.payload.title}</DialogDescription></DialogHeader><p className="text-sm leading-6 text-[#65768b]">{review?"실제 근거와 수정 결과를 확인하고 의견을 남기세요.":"무엇을 직접 했는지, 근거는 무엇인지, 이전과 무엇이 달라졌는지 적으세요."}</p>{review&&<Choice label="교사 확인 상태" value={status} onChange={setStatus} items={[["confirmed","근거 확인됨"],["revision_requested","추가 확인·보완 필요"]]}/>}<Textarea aria-label={review?"교사 피드백":"실행 결과"} value={text} onChange={e=>setText(e.target.value)} className="min-h-44 text-base" maxLength={review?5000:8000}/>{error&&<p role="alert" className="text-sm text-rose-800">{error}</p>}<DialogFooter><Button disabled={busy||!text.trim()} onClick={()=>void save()}>{busy?"저장 중…":review?"확인 결과 저장":"결과 제출"}</Button></DialogFooter></DialogContent></Dialog>;
}
