"use client";

import { clientId } from "@/lib/client-id";
import * as React from "react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Card,CardContent } from "@/components/ui/card";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from "@/components/ui/table";
import type { PortalData,Student } from "@/lib/portal-types";
import { documentStages,gradingSystems,guidancePayloadSchema,studentPlan,type GuidanceEntry,type GuidancePayload } from "@/lib/guidance";
import { courseRuleCheck, criterionApplicability } from "@/lib/course-planning";
import { Choice,Field,type GuidanceSave } from "@/app/guidance-view";

const availability={offered:"학교 개설",shared:"공동교육과정",unavailable:"미개설",unknown:"확인 필요"};
export function PlanningView({data,students,selectedStudentId,onSelect,busy,onSave}:{data:PortalData;students:Student[];selectedStudentId:number|null;onSelect:(id:number)=>void;busy:boolean;onSave:GuidanceSave}){
  const student=students.find(s=>s.id===selectedStudentId)??students[0];const [offer,setOffer]=React.useState<GuidanceEntry|"new"|null>(null);
  const offers=data.guidance.filter(e=>e.kind==="course_offering"&&e.payload.status!=="closed");const admin=data.viewer.role==="admin";
  return <div className="space-y-5"><div className="flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-bold">진학·과목 계획</h1><p className="mt-3 text-base leading-7 text-[#65768b]">목표 입학연도와 학교에서 선택할 수 있는 과목을 함께 확인합니다.</p></div>{student&&<div className="w-full sm:w-64"><Choice label="계획할 학생" value={String(student.id)} onChange={v=>onSelect(Number(v))} items={students.map(s=>[String(s.id),`${s.name} · ${s.studentNumber}`])}/></div>}</div>
    {student?<StudentPlanForm key={`${student.id}:${studentPlan(data.guidance,student.id)?.revision??0}`} data={data} student={student} offers={offers} busy={busy} onSave={onSave}/>:<p className="rounded-xl border bg-white p-5">등록된 학생이 없습니다.</p>}
    <Card><CardContent className="space-y-4 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">학교 개설 과목</h2>{admin&&<Button onClick={()=>setOffer("new")}>개설 과목 등록</Button>}</div>{!offers.length?<p className="text-sm leading-6 text-[#65768b]">관리자가 학교 교육과정 편제표를 확인해 개설 과목을 등록하면 계획에서 선택할 수 있습니다.</p>:<div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>과목·교육과정</TableHead><TableHead>시기</TableHead><TableHead>학점</TableHead><TableHead>개설</TableHead><TableHead>선수 조건·안내</TableHead>{admin&&<TableHead>관리</TableHead>}</TableRow></TableHeader><TableBody>{offers.map(e=>{const p=e.payload,o=p.offering!;return <TableRow key={e.entityKey}><TableCell><p className="font-semibold">{p.title}</p><p className="text-sm text-[#65768b]">{o.subjectGroup} · {o.curriculum}</p></TableCell><TableCell>{o.schoolYear} · {o.grade}-{o.semester}</TableCell><TableCell>{o.credits??"미확인"}</TableCell><TableCell>{availability[o.availability]}</TableCell><TableCell className="max-w-80 whitespace-normal text-sm leading-6">{o.prerequisites||"선수 조건 미등록"}{p.text&&<p>{p.text}</p>}</TableCell>{admin&&<TableCell><Button variant="outline" size="sm" onClick={()=>setOffer(e)}>수정</Button></TableCell>}</TableRow>;})}</TableBody></Table></div>}</CardContent></Card>
    {admin&&student&&<EnrollmentForm key={`${student.id}:${student.classId}`} data={data} student={student} busy={busy} onSave={onSave}/>}
    {offer&&<OfferingForm entry={offer==="new"?undefined:offer} busy={busy} onSave={onSave} onClose={()=>setOffer(null)}/>}
  </div>;
}
function StudentPlanForm({data,student,offers,busy,onSave}:{data:PortalData;student:Student;offers:GuidanceEntry[];busy:boolean;onSave:GuidanceSave}){
  const entry=studentPlan(data.guidance,student.id),classroom=data.classes.find(c=>c.id===student.classId),staff=data.viewer.role!=="student";
  const [plan,setPlan]=React.useState<NonNullable<GuidancePayload["plan"]>>(()=>entry?.payload.plan??{admissionsYear:null,curriculum:"",gradingSystem:"unknown",institution:"",admissionTrack:"",department:"",directionGoal:"",careerGoal:"",semesterGoal:"",immediateGoal:"",materialIds:[],offeringKeys:[]});
  const [reason,setReason]=React.useState(entry?.payload.text??""),[error,setError]=React.useState("");
  const put=<K extends keyof typeof plan>(key:K,value:(typeof plan)[K])=>setPlan(p=>({...p,[key]:value}));
  const references=data.guidance.filter(e=>e.kind==="reference"&&e.payload.reference?.approval==="approved"&&data.referenceMaterials.some(m=>m.id===e.payload.reference?.materialId&&m.status==="active"));
  const selectedCriteria=data.appliedCriteria.filter(c=>plan.materialIds.includes(c.materialId));
  const courses=data.academicCourses.filter(c=>c.studentId===student.id);
  const save=async()=>{try{await onSave({kind:"student_plan",studentId:student.id,entityKey:`plan:${student.id}`,expectedRevision:entry?.revision??0,includeInWork:false,payload:{title:"진학·과목 선택 계획",text:reason,plan}});}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}};
  return <><Card><CardContent className="space-y-4 p-5"><h2 className="text-lg font-semibold">{student.name}의 계획</h2><p className="text-sm text-[#65768b]">현재 {classroom?.schoolYear}학년도 {classroom?.grade}학년입니다. 목표 입학연도와 실제 교육과정은 따로 확인해 입력하세요.</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    <Field label="목표 입학연도"><Input aria-label="목표 입학연도" type="number" min={2022} max={2100} value={plan.admissionsYear??""} onChange={e=>put("admissionsYear",e.target.value?Number(e.target.value):null)} placeholder="확인 후 입력"/></Field>
    <Field label="적용 교육과정"><Input aria-label="학생 적용 교육과정" value={plan.curriculum} onChange={e=>put("curriculum",e.target.value)} placeholder="예: 2022 개정"/></Field><Field label="성적 체계"><Choice label="학생 성적 체계" value={plan.gradingSystem} onChange={v=>put("gradingSystem",v as typeof plan.gradingSystem)} items={Object.entries(gradingSystems)}/></Field>
    <Field label="관심 대학 · 선택"><Input aria-label="관심 대학" value={plan.institution} onChange={e=>put("institution",e.target.value)}/></Field><Field label="전형 · 선택"><Input aria-label="관심 전형" value={plan.admissionTrack} onChange={e=>put("admissionTrack",e.target.value)}/></Field><Field label="모집단위 · 선택"><Input aria-label="관심 모집단위" value={plan.department} onChange={e=>put("department",e.target.value)}/></Field>
  </div><Field label="선택 이유·확인할 조건"><Textarea aria-label="과목과 진학 선택 이유" value={reason} onChange={e=>setReason(e.target.value)} placeholder="관심의 변화, 배우고 싶은 내용, 시간표와 개설 여건 등을 적습니다."/></Field>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">방향에서 이번 주 행동까지 · 4단계 목표</summary><div className="mt-4 grid gap-4 sm:grid-cols-2">{([["directionGoal","쌓아가고 싶은 탐구 방향"],["careerGoal","진로·학과를 탐색하는 목표"],["semesterGoal","이번 학기 확인할 목표"],["immediateGoal","지금 바로 할 수 있는 행동"]] as const).map(([key,label])=><Field key={key} label={label}><Textarea aria-label={label} value={plan[key]??""} maxLength={1500} onChange={e=>put(key,e.target.value)}/></Field>)}</div><p className="mt-3 text-sm text-[#65768b]">목표는 바꿀 수 있습니다. 실제 실행 결과와 피드백은 ‘다음 행동’에 남깁니다.</p></details>
    {offers.length>0&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">계획에 담을 학교 과목 선택 · {plan.offeringKeys.length}개</summary><div className="mt-4 grid gap-3 sm:grid-cols-2">{offers.map(e=><label key={e.entityKey} className="flex items-start gap-2 rounded-xl bg-[#f7f9fc] p-3 text-sm leading-6"><Checkbox checked={plan.offeringKeys.includes(e.entityKey)} onCheckedChange={v=>put("offeringKeys",v===true?[...plan.offeringKeys,e.entityKey]:plan.offeringKeys.filter(k=>k!==e.entityKey))}/><span>{e.payload.title} · {e.payload.offering!.schoolYear} {e.payload.offering!.grade}-{e.payload.offering!.semester}<br/>{availability[e.payload.offering!.availability]} · {e.payload.offering!.credits??"미확인"}학점</span></label>)}</div><p className="mt-3 text-sm text-[#65768b]">여기서 고른 과목은 계획입니다. 실제 수강·이수학점은 학생부 원문에서 별도로 확인합니다.</p></details>}
    {staff&&<details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">이 학생에게 적용할 승인 자료 선택</summary><div className="mt-3 space-y-3">{references.length?references.map(e=><label key={e.entityKey} className="flex items-center gap-2 text-sm"><Checkbox checked={plan.materialIds.includes(e.payload.reference!.materialId)} onCheckedChange={v=>put("materialIds",v===true?[...plan.materialIds,e.payload.reference!.materialId]:plan.materialIds.filter(id=>id!==e.payload.reference!.materialId))}/>{e.payload.title} · {e.payload.reference!.versionLabel}</label>):<p className="text-sm">공용 평가 자료실에서 관리자의 판본 검토가 필요합니다.</p>}</div></details>}
    {error&&<p role="alert" className="text-sm text-rose-800">{error}</p>}<Button disabled={busy} onClick={()=>void save()}>{busy?"저장 중…":"계획 저장"}</Button>
  </CardContent></Card>
  {selectedCriteria.map(c=><Card key={c.materialId}><CardContent className="space-y-3 p-5"><div className="flex flex-wrap gap-2"><Badge variant="outline">{documentStages[c.reference.stage]}</Badge><Badge variant="outline">{c.reference.versionLabel}</Badge></div><h2 className="font-semibold">{c.title}</h2><p className="text-sm leading-6 text-[#65768b]">{c.reference.department||"모집단위 공통"} · {c.reference.curriculum||"교육과정 확인 필요"}. 원문 조건과 예외를 함께 확인하세요.</p>{c.reference.rules.length?c.reference.rules.map((r,i)=>{const issue=criterionApplicability(c,plan);const result=issue?{state:issue,detail:"조건 대조를 보류했습니다. 적용 대상을 먼저 확인하세요."}:courseRuleCheck(r,courses,true);return <div key={i} className="space-y-2 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><p className="font-semibold">{r.label}</p><Badge variant="outline">{result.state}</Badge></div><p className="text-sm leading-6">{result.detail}</p><p className="text-sm leading-6 text-[#65768b]">원문 {r.sourcePage}쪽 · {r.description}</p></div>;}):<p className="text-sm">구조화된 과목 기준이 없습니다. 담당 교사가 원문을 확인하여 등록할 수 있습니다.</p>}{c.reference.sourceUrl&&<a href={c.reference.sourceUrl} target="_blank" rel="noreferrer" className="inline-block text-sm text-[#2457d6] underline">공식 자료 확인</a>}</CardContent></Card>)}</>;
}
function OfferingForm({entry,busy,onSave,onClose}:{entry?:GuidanceEntry;busy:boolean;onSave:GuidanceSave;onClose:()=>void}){
  const [title,setTitle]=React.useState(entry?.payload.title??""),[note,setNote]=React.useState(entry?.payload.text??""),[error,setError]=React.useState("");
  const [o,setO]=React.useState<NonNullable<GuidancePayload["offering"]>>(()=>entry?.payload.offering??{schoolYear:new Date().getFullYear(),grade:2,semester:1,subjectGroup:"",curriculum:"",credits:null,availability:"unknown",prerequisites:""});const key=React.useRef(entry?.entityKey??clientId());
  const put=<K extends keyof typeof o>(k:K,v:(typeof o)[K])=>setO(x=>({...x,[k]:v}));
  const save=async()=>{try{await onSave({kind:"course_offering",studentId:null,entityKey:key.current,expectedRevision:entry?.revision??0,payload:{title,text:note,offering:o}});onClose();}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}};
  return <Dialog open onOpenChange={v=>{if(!v&&!busy)onClose();}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>학교 교육과정 개설 과목</DialogTitle><DialogDescription>학교 편제표와 실제 개설 여부를 확인한 내용을 등록합니다.</DialogDescription></DialogHeader><div className="grid gap-4 sm:grid-cols-2"><Field label="과목명"><Input aria-label="개설 과목명" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="과목군"><Input aria-label="과목군" value={o.subjectGroup} onChange={e=>put("subjectGroup",e.target.value)}/></Field><Field label="교육과정"><Input aria-label="개설 교육과정" value={o.curriculum} onChange={e=>put("curriculum",e.target.value)}/></Field><Field label="학년도"><Input aria-label="개설 학년도" type="number" value={o.schoolYear} onChange={e=>put("schoolYear",Number(e.target.value))}/></Field><Choice label="개설 학년" value={String(o.grade)} onChange={v=>put("grade",Number(v))} items={[["1","1학년"],["2","2학년"],["3","3학년"]]}/><Choice label="개설 학기" value={String(o.semester)} onChange={v=>put("semester",Number(v))} items={[["1","1학기"],["2","2학기"]]}/><Field label="학점 · 미확인은 비움"><Input aria-label="개설 과목 학점" type="number" min={0} max={20} value={o.credits??""} onChange={e=>put("credits",e.target.value?Number(e.target.value):null)}/></Field><Choice label="개설 여부" value={o.availability} onChange={v=>put("availability",v as typeof o.availability)} items={Object.entries(availability)}/></div><Field label="선수 조건"><Textarea aria-label="선수 조건" value={o.prerequisites} onChange={e=>put("prerequisites",e.target.value)}/></Field><Field label="추가 안내·편제표 근거"><Textarea aria-label="개설 과목 안내" value={note} onChange={e=>setNote(e.target.value)}/></Field>{error&&<p role="alert" className="text-sm text-rose-800">{error}</p>}<Button disabled={busy||!title.trim()} onClick={()=>void save()}>개설 과목 저장</Button></DialogContent></Dialog>;
}
function EnrollmentForm({data,student,busy,onSave}:{data:PortalData;student:Student;busy:boolean;onSave:GuidanceSave}){
  const [classId,setClassId]=React.useState("none"),[number,setNumber]=React.useState(student.studentNumber),[error,setError]=React.useState("");const current=data.guidance.find(e=>e.kind==="enrollment"&&e.studentId===student.id);
  const save=async()=>{try{await onSave({kind:"enrollment",studentId:student.id,entityKey:`enrollment:${student.id}`,expectedRevision:current?.revision??0,payload:{title:"학급 이동",enrollment:{fromClassId:student.classId,toClassId:Number(classId),previousNumber:student.studentNumber,studentNumber:number}}});}catch(e){setError(e instanceof Error?e.message:"이동하지 못했습니다.");}};
  return <details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-semibold">관리자 · 진급·학급 이동</summary><p className="mt-3 text-sm leading-6 text-[#65768b]">동일 학생의 고정 ID와 원본·분석·피드백을 유지합니다. 이동 후에는 새 학급 담당자가 열람합니다. 대상 학급을 먼저 학교 설정에서 등록하세요.</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Choice label="이동 학급" value={classId} onChange={setClassId} items={[["none","이동할 학급"],...data.classes.filter(c=>c.id!==student.classId).map(c=>[String(c.id),`${c.schoolYear} · ${c.name}`] as [string,string])]}/><Input aria-label="이동 후 학번" value={number} maxLength={30} onChange={e=>setNumber(e.target.value)}/><Button disabled={busy||classId==="none"||!number.trim()} onClick={()=>void save()}>학급 이동·이력 저장</Button></div>{current&&<p className="mt-3 text-sm">마지막 이동: {current.createdAt.slice(0,10)} · 이전 학번 {current.payload.enrollment?.previousNumber}</p>}{error&&<p role="alert" className="mt-3 text-sm text-rose-800">{error}</p>}</details>;
}
