"use client";
import * as React from "react";
import { Download, Upload, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import type { PortalData } from "@/lib/portal-types";
import { referenceCategories, referenceKey, MAX_REFERENCE_SELECTION } from "@/lib/reference-materials";

export function ReferenceMaterialsView({data,busy,onAction,onUploaded}:{data:PortalData;busy:boolean;onAction:(body:Record<string,unknown>)=>Promise<unknown>;onUploaded:()=>Promise<void>}) {
  const [query,setQuery]=React.useState(""),[showArchived,setShowArchived]=React.useState(false),[uploading,setUploading]=React.useState(false),[error,setError]=React.useState("");
  const [selected,setSelected]=React.useState(data.selectedReferenceMaterialIds);
  const signature=data.selectedReferenceMaterialIds.join(",");
  React.useEffect(()=>{setSelected(signature?signature.split(",").map(Number):[]);},[signature]);
  const isAdmin=data.viewer.role==="admin", formRef=React.useRef<HTMLFormElement>(null), lock=React.useRef(false);
  const materials=data.referenceMaterials.filter(row=>(showArchived||row.status==="active")&&`${row.title} ${row.institution} ${row.admissionTrack} ${row.admissionsYear??""}`.toLowerCase().includes(query.toLowerCase()));
  const dirty=[...selected].sort().join(",")!==[...data.selectedReferenceMaterialIds].sort().join(",");
  const toggle=(id:number,checked:boolean)=>{setError("");if(checked&&selected.length>=MAX_REFERENCE_SELECTION){setError("평가 자료는 최대 20건까지 선택하세요.");return;}setSelected(values=>checked?[...values,id]:values.filter(value=>value!==id));};
  const upload=async(event:React.FormEvent<HTMLFormElement>)=>{
    event.preventDefault();if(lock.current)return;lock.current=true;setUploading(true);setError("");
    try{const response=await fetch("/api/reference-materials",{method:"POST",body:new FormData(event.currentTarget)});const result=await response.json() as {error?:string};if(!response.ok)throw new Error(result.error||"자료를 등록하지 못했습니다.");formRef.current?.reset();await onUploaded();toast.success("공용 평가 자료를 등록했습니다.");}catch(e){setError(e instanceof Error?e.message:"자료를 등록하지 못했습니다.");}finally{lock.current=false;setUploading(false);}
  };
  return <div className="space-y-5"><div><h1 className="text-3xl font-bold tracking-tight">공용 평가 자료실</h1><p className="mt-3 text-base leading-7 text-[#65768b]">관리자가 모집요강·평가 기준을 한 번 등록하면 교사는 학생 분석에 반복해서 사용할 수 있습니다.</p></div>
    <Card><CardContent className="space-y-3 p-5"><h2 className="font-bold">Work에서 함께 사용할 자료</h2><p className="text-sm leading-6 text-[#65768b]">자료를 선택해 저장하면 내 Work 요청문에 목록과 출처 ID가 자동으로 들어갑니다. 처음 한 번 자료 묶음을 받아 Work에 전달하세요. 같은 Work 공간에서 이미 읽을 수 있는 자료는 다시 첨부하지 않아도 됩니다.</p><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{selected.length} / 20건</Badge><Button disabled={busy||uploading||!dirty} onClick={async()=>{try{await onAction({action:"setReferenceSelection",materialIds:selected});}catch(e){setError(e instanceof Error?e.message:"선택을 저장하지 못했습니다.");}}}>분석 자료 선택 저장</Button><Button asChild variant="outline" disabled={!selected.length}><a aria-disabled={!selected.length} onClick={event=>{if(!selected.length)event.preventDefault();}} href={`/api/reference-materials/bundle?ids=${selected.join(",")}`}><Download/>선택 자료 한 번에 받기</a></Button>{dirty&&<span className="text-sm text-amber-800">선택 변경 후 저장하세요.</span>}</div></CardContent></Card>
    {isAdmin&&<details className="rounded-xl border bg-white p-5"><summary className="cursor-pointer font-bold">새 공용 자료 등록</summary><form ref={formRef} onSubmit={event=>void upload(event)} className="mt-4 grid gap-4 sm:grid-cols-2"><div className="grid gap-2 sm:col-span-2"><Label htmlFor="ref-title">자료 제목</Label><Input id="ref-title" name="title" required maxLength={300} disabled={uploading}/></div><div className="grid gap-2"><Label htmlFor="ref-institution">대학·기관</Label><Input id="ref-institution" name="institution" maxLength={150} disabled={uploading}/></div><div className="grid gap-2"><Label htmlFor="ref-year">모집 학년도 · 공통 자료는 비워두세요</Label><Input id="ref-year" name="admissionsYear" type="number" min={2022} max={2100} disabled={uploading}/></div><div className="grid gap-2"><Label htmlFor="ref-track">전형</Label><Input id="ref-track" name="admissionTrack" maxLength={150} disabled={uploading}/></div><div className="grid gap-2"><Label htmlFor="ref-category">자료 종류</Label><select id="ref-category" name="category" disabled={uploading} className="h-10 rounded-md border bg-white px-3 text-sm">{Object.entries(referenceCategories).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="ref-note">사용 안내 · 선택</Label><Input id="ref-note" name="note" maxLength={2000} disabled={uploading}/></div><div className="grid gap-2 sm:col-span-2"><Label htmlFor="ref-file">자료 파일 · 최대 20MB</Label><Input id="ref-file" name="file" type="file" required accept=".pdf,.hwp,.hwpx,.docx,.pptx,.txt,.md" disabled={uploading}/></div><Button className="bg-[#173a73] sm:col-span-2" disabled={uploading||busy}><Upload/>{uploading?"자료 등록 중…":"공용 자료 등록"}</Button><p className="text-sm text-[#65768b] sm:col-span-2">개정 자료는 새 파일로 등록하세요. 이전 파일과 분석 출처는 보존됩니다.</p></form></details>}
    <div className="flex flex-wrap items-center gap-3"><Search className="size-4"/><Input className="min-w-52 flex-1 bg-white" aria-label="대학·학년도·자료 검색" placeholder="대학, 전형, 학년도, 제목 검색" value={query} onChange={e=>setQuery(e.target.value)}/><label className="flex items-center gap-2 text-sm"><Checkbox checked={showArchived} onCheckedChange={value=>setShowArchived(value===true)}/>보관한 자료 표시</label></div>
    {error&&<p role="alert" className="rounded-xl bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
    {!materials.length&&<p className="rounded-xl border bg-white p-6 text-[#65768b]">{query?"검색 조건에 맞는 자료가 없습니다.":"등록된 공용 평가 자료가 없습니다. 관리자가 자료를 등록하면 여기에서 선택할 수 있습니다."}</p>}
    {materials.map(row=><Card key={row.id}><CardContent className="flex items-start gap-3 p-5"><Checkbox className="mt-1" aria-label={`${row.title} 선택`} checked={selected.includes(row.id)} disabled={busy||uploading||row.status!=="active"} onCheckedChange={value=>toggle(row.id,value===true)}/><div className="min-w-0 flex-1"><h2 className="break-words font-bold">{row.title}</h2><p className="mt-1 text-sm text-[#65768b]">{row.institution||"공통 자료"} · {row.admissionsYear?`${row.admissionsYear}학년도`:"학년도 공통"} · {row.admissionTrack||"전형 공통"}</p><div className="mt-2 flex flex-wrap gap-2"><Badge variant="outline">{referenceKey(row.id)}</Badge><Badge variant="outline">{referenceCategories[row.category]}</Badge>{row.status==="archived"&&<Badge variant="outline">보관 자료</Badge>}</div>{row.note&&<p className="mt-3 text-sm leading-6">{row.note}</p>}<div className="mt-3 flex flex-wrap gap-2"><Button asChild variant="outline" size="sm"><a href={`/api/reference-materials/${row.id}`}><Download/>원문 받기</a></Button>{isAdmin&&<Button variant="ghost" size="sm" disabled={busy||uploading} onClick={async()=>{try{await onAction({action:"setReferenceStatus",materialId:row.id,status:row.status==="active"?"archived":"active"});}catch(e){setError(e instanceof Error?e.message:"상태를 변경하지 못했습니다.");}}}>{row.status==="active"?"이전 자료로 보관":"사용 자료로 복원"}</Button>}</div></div></CardContent></Card>)}
  </div>;
}
