"use client";

import * as React from "react";
import { ArrowRight, Plus, MessageSquareText, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { clientId } from "@/lib/client-id";
import { guidancePayloadSchema,guidanceKinds,guidanceStatuses,type GuidanceEntry,type GuidancePayload } from "@/lib/guidance";
import { studentKinds,studentOverview,type StudentKind,type StudentView } from "@/lib/student-overview";
import type { PortalData } from "@/lib/portal-types";

export type StudentNavigate=(view:StudentView,entryKey?:string)=>void;
export type StudentSave=(body:Record<string,unknown>)=>Promise<void>;
export const studentCard="rounded-2xl border border-[#e0e5ed] bg-white p-5 sm:p-6";
export function StudentHeading({eyebrow,title,children}:{eyebrow?:string;title:string;children?:React.ReactNode}) {return <div><p className="text-sm font-medium text-[#5466a8]">{eyebrow??"나의 탐구 기록"}</p><h1 className="mt-2 text-2xl font-semibold tracking-tight sm:text-3xl">{title}</h1>{children&&<p className="mt-3 max-w-3xl text-base leading-7 text-[#627086]">{children}</p>}</div>;}
function Status({entry}:{entry:GuidanceEntry}) {return <span className={`inline-flex rounded-md px-2 py-1 text-sm font-medium ${entry.payload.status==="revision_requested"?"bg-amber-50 text-amber-900":entry.payload.status==="confirmed"?"bg-emerald-50 text-emerald-800":"bg-[#eff2f7] text-[#52617a]"}`}>{guidanceStatuses[entry.payload.status]}</span>;}
function ShortEntry({entry,navigate}:{entry:GuidanceEntry;navigate:StudentNavigate}) {return <button onClick={()=>navigate("journal",entry.entityKey)} className="group flex w-full items-center gap-4 border-t border-[#e8ecf2] py-4 text-left first:border-t-0"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap items-center gap-2"><Status entry={entry}/><span className="text-xs text-[#627086]">{guidanceKinds[entry.kind]}{entry.payload.subject&&` · ${entry.payload.subject}`}</span></div><p className="break-words font-medium">{entry.payload.title}</p>{entry.payload.dueDate&&<p className="mt-2 flex items-center gap-1 text-xs text-[#627086]"><CalendarDays className="size-3"/>목표일 {entry.payload.dueDate}</p>}</div><ArrowRight className="size-4 shrink-0 text-[#627086] transition group-hover:translate-x-1"/></button>;}

export function StudentHome({data,navigate,readOnly}:{data:PortalData;navigate:StudentNavigate;readOnly:boolean}) {
  const summary=studentOverview(data),classroom=data.classes[0];
  return <><StudentHeading eyebrow={`${classroom?.name??"나의 학급"} · ${summary.student.studentNumber}`} title={`${summary.student.name}님의 오늘`}>작은 질문 하나를 남기고, 실제로 해 본 일과 달라진 생각을 이어가세요.</StudentHeading>
    <div className="grid gap-4 sm:grid-cols-3">{[{label:"이어갈 기록",count:summary.next.length,note:"작성 중인 질문과 다음 할 일",view:"journal"},{label:"선생님 확인 대기",count:summary.submitted.length,note:"실행 결과를 제출한 기록",view:"journal"},{label:"보완할 기록",count:summary.revisions.length,note:"피드백을 보고 다시 이어가기",view:"feedback"}].map(item=><button key={item.label} onClick={()=>navigate(item.view as StudentView)} className={`${studentCard} text-left transition hover:border-[#9aaaca]`}><p className="text-sm text-[#627086]">{item.label}</p><p className="mt-2 text-3xl font-semibold tabular-nums">{item.count}<span className="ml-1 text-sm font-normal">개</span></p><p className="mt-2 text-xs text-[#627086]">{item.note}</p></button>)}</div>
    <div className="grid items-start gap-5 xl:grid-cols-[1.35fr_1fr]"><section className={studentCard}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">지금 이어갈 일</h2>{!readOnly&&<Button size="sm" onClick={()=>navigate("journal","new")}><Plus/>새 질문</Button>}</div>{summary.overdue.length>0&&<p className="mt-3 text-sm leading-6 text-amber-900">목표일이 지난 기록 {summary.overdue.length}개가 있습니다. 진행 상황을 적거나 목표일을 다시 정해 보세요.</p>}<div className="mt-3">{summary.next.length?summary.next.slice(0,3).map(e=><ShortEntry key={e.entityKey} entry={e} navigate={navigate}/>):<div className="py-6 text-base leading-7 text-[#627086]">이어갈 기록이 아직 없습니다.<br/>수업에서 궁금했던 점부터 하나 남겨 보세요.</div>}</div><Button variant="ghost" className="mt-2" onClick={()=>navigate("journal")}>내 기록 모두 보기<ArrowRight/></Button></section>
    <section className={studentCard}><h2 className="text-lg font-semibold">선생님이 남긴 피드백</h2>{summary.feedback[0]?<div className="mt-4"><Status entry={summary.feedback[0]}/><p className="mt-3 font-medium">{summary.feedback[0].payload.title}</p><p className="mt-3 whitespace-pre-wrap break-words text-sm leading-7 text-[#52617a]">{summary.feedback[0].payload.feedback}</p><Button variant="outline" className="mt-4" onClick={()=>navigate("journal",summary.feedback[0].entityKey)}>이 기록 이어가기</Button></div>:<p className="mt-4 text-base leading-7 text-[#627086]">실행 결과를 제출하면 선생님이 확인한 내용과 보완할 점을 여기에서 볼 수 있습니다.</p>}</section></div>
    <section className={`${studentCard} border-l-4 border-l-[#7184bb]`}><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">나의 탐구 방향</h2><Button size="sm" variant="ghost" onClick={()=>navigate("fingerprint")}>연구 기록 열기<ArrowRight/></Button></div><p className="mt-3 text-base leading-7 text-[#52617a]">{summary.profile?.oneLineProfile??"학생부 분석 결과가 연결되면 주요 관심 키워드와 탐구 흐름을 볼 수 있습니다. 질문 기록은 먼저 시작할 수 있습니다."}</p><div className="mt-4 flex flex-wrap gap-2">{summary.keywords.map(k=><span key={k.id} className="rounded-full bg-[#f0f3fa] px-3 py-1.5 text-sm text-[#4c5e8a]">{k.keyword}</span>)}</div>{summary.profile&&<p className="mt-4 text-xs leading-6 text-[#627086]">{summary.profile.sourceYears.join("·")}학년도 자료 기준 · {summary.profile.versionLabel} · 분석 내용이 원문과 다르면 정정 요청을 남기세요.</p>}</section>
  </>;
}

export function StudentFeedback({data,navigate}:{data:PortalData;navigate:StudentNavigate}) {
 const entries=studentOverview(data).feedback;
 return <><StudentHeading title="선생님 피드백">확인받은 점과 다음에 보완할 점을 읽고, 같은 기록에서 실행 결과를 이어서 제출하세요.</StudentHeading>{entries.length?entries.map(e=><article key={e.entityKey} className={studentCard}><div className="flex flex-wrap items-center gap-2"><Status entry={e}/><span className="text-xs text-[#627086]">{e.payload.reviewedBy||"담당 선생님"}{e.payload.reviewedAt&&` · ${e.payload.reviewedAt.slice(0,10)}`}</span></div><h2 className="mt-3 text-lg font-semibold">{e.payload.title}</h2><p className="mt-3 whitespace-pre-wrap break-words text-base leading-7 text-[#52617a]">{e.payload.feedback}</p>{e.payload.status==="submitted"&&<p className="mt-3 text-sm text-[#627086]">위 피드백 이후 결과를 다시 제출했습니다. 선생님의 다음 확인을 기다리고 있습니다.</p>}<Button className="mt-4" variant="outline" onClick={()=>navigate("journal",e.entityKey)}>기록과 제출 내용 확인<ArrowRight/></Button></article>):<p className={studentCard}>아직 학생에게 공유된 피드백이 없습니다.</p>}</>;
}

export function StudentJournal({data,entryKey,navigate,onSave,busy,readOnly,onHistory}:{data:PortalData;entryKey?:string;navigate:StudentNavigate;onSave:StudentSave;busy:boolean;readOnly:boolean;onHistory:(key:string)=>Promise<GuidanceEntry[]>}) {
  const [query,setQuery]=React.useState(""),[filter,setFilter]=React.useState("all");
  const [editor,setEditor]=React.useState<{entry?:GuidanceEntry;kind:StudentKind;parent?:GuidanceEntry}|null>(null),[reply,setReply]=React.useState<GuidanceEntry|null>(null),[history,setHistory]=React.useState<GuidanceEntry[]|null>(null),[historyError,setHistoryError]=React.useState(""),[historyBusy,setHistoryBusy]=React.useState(false);
  const entries=studentOverview(data).entries;
  React.useEffect(()=>{if(entryKey==="new"&&!readOnly)setEditor({kind:"question"});},[entryKey,readOnly]);
  const focused=entryKey&&entryKey!=="new"?entries.find(e=>e.entityKey===entryKey):null;
  const visible=focused?[focused]:entries.filter(e=>(filter==="all"||e.payload.status===filter)&&`${e.payload.title} ${e.payload.text} ${e.payload.subject}`.toLowerCase().includes(query.trim().toLowerCase()));
  const closeEditor=()=>{setEditor(null);if(entryKey==="new")navigate("journal");};
  return <><div className="flex flex-wrap items-end justify-between gap-4"><StudentHeading title="내 질문·실행 기록">궁금했던 이유와 해 본 일을 남깁니다. 저장한 뒤 실행 결과를 선생님께 제출할 수 있습니다.</StudentHeading>{!readOnly&&<Button disabled={busy} onClick={()=>setEditor({kind:"question"})}><Plus/>기록 작성</Button>}</div>
    {entryKey&&entryKey!=="new"?<div className="flex flex-wrap items-center gap-3"><Button variant="outline" onClick={()=>navigate("journal")}>전체 기록으로</Button>{!focused&&<p role="alert" className="text-sm text-[#627086]">요청한 기록을 찾을 수 없습니다. 공유 상태가 바뀌었을 수 있습니다.</p>}</div>:<div className="flex flex-wrap gap-3"><Input className="min-w-48 flex-1 bg-white" aria-label="내 기록 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="질문·내용·과목 검색"/><select aria-label="기록 상태 필터" className="min-h-10 rounded-lg border bg-white px-3 text-sm" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">모든 상태</option>{Object.entries(guidanceStatuses).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}
    {!visible.length&&(!entryKey||entryKey==="new")&&<p className={studentCard}>{query||filter!=="all"?"검색 조건에 맞는 기록이 없습니다.":"아직 작성한 기록이 없습니다. 첫 질문을 남겨 보세요."}</p>}
    {visible.map(e=>{const p=e.payload,canReply=!readOnly&&Object.hasOwn(studentKinds,e.kind)&&!["confirmed","closed"].includes(p.status),canEdit=canReply&&p.ownerId===data.viewer.id;const parent=entries.find(r=>r.entityKey===p.parentKey);return <article key={e.entityKey} className={studentCard}><div className="flex flex-wrap items-center gap-2"><Status entry={e}/><span className="text-xs text-[#627086]">{guidanceKinds[e.kind]}{p.subject&&` · ${p.subject}`} · {e.createdAt.slice(0,10)}</span></div><h2 className="mt-3 break-words text-lg font-semibold">{p.title}</h2>{parent&&<button className="mt-3 text-left text-sm text-[#5466a8] underline" onClick={()=>navigate("journal",parent.entityKey)}>이전 질문 · {parent.payload.title}</button>}
      {p.text&&<p className="mt-3 whitespace-pre-wrap break-words text-base leading-7 text-[#52617a]">{p.text}</p>}
      {(p.method||p.result||p.remainingQuestion||p.sourceNote||p.dueDate)&&<dl className="mt-4 grid gap-3 rounded-xl bg-[#f6f8fb] p-4 text-sm leading-6">{[["탐구 방법",p.method],["알게 된 점",p.result],["남은 질문",p.remainingQuestion],["근거·자료",p.sourceNote],["목표일",p.dueDate]].filter(([,v])=>v).map(([label,value])=><div key={label}><dt className="font-medium">{label}</dt><dd className="mt-1 whitespace-pre-wrap break-words text-[#627086]">{value}</dd></div>)}</dl>}
      {p.response&&<div className="mt-4 rounded-xl border border-[#dbe3f0] p-4"><h3 className="text-sm font-semibold">내가 제출한 실행 결과</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-[#52617a]">{p.response}</p></div>}
      {p.feedback&&<div className="mt-4 rounded-xl bg-[#eff4f1] p-4"><h3 className="flex items-center gap-2 text-sm font-semibold text-[#35664c]"><MessageSquareText className="size-4"/>선생님 피드백</h3><p className="mt-2 whitespace-pre-wrap break-words text-sm leading-7 text-[#42634f]">{p.feedback}</p></div>}
      <div className="mt-5 flex flex-wrap gap-2">{canReply&&<Button size="sm" disabled={busy} onClick={()=>setReply(e)}>{p.status==="revision_requested"?"보완 결과 제출":p.status==="submitted"?"제출 결과 보완":"실행 결과 제출"}</Button>}{canEdit&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setEditor({entry:e,kind:e.kind as StudentKind})}>기록 수정</Button>}{!readOnly&&<Button size="sm" variant="outline" disabled={busy} onClick={()=>setEditor({kind:"question",parent:e})}>다음 질문 연결</Button>}<Button size="sm" variant="ghost" disabled={historyBusy} onClick={()=>{setHistoryError("");setHistoryBusy(true);void onHistory(e.entityKey).then(setHistory).catch(err=>setHistoryError(err.message)).finally(()=>setHistoryBusy(false));}}>변경 이력</Button></div>
    </article>;})}
    {historyError&&<p role="alert" className="text-sm text-rose-800">{historyError}</p>}
    {editor&&<StudentEditor key={editor.entry?.entityKey??editor.parent?.entityKey??"new"} {...editor} onSave={onSave} busy={busy} onClose={closeEditor}/>}
    {reply&&<StudentReply key={reply.entityKey} entry={reply} onSave={onSave} busy={busy} onClose={()=>setReply(null)}/>}
    <Dialog open={history!==null} onOpenChange={open=>{if(!open)setHistory(null);}}><DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>공유된 변경 이력</DialogTitle><DialogDescription>학생에게 공유된 버전의 작성·제출·피드백을 확인합니다.</DialogDescription></DialogHeader>{history?.map(e=><article key={e.id} className="space-y-2 border-t py-3 text-sm leading-6"><p className="font-medium">{e.revision}번째 저장 · {guidanceStatuses[e.payload.status]} · {e.actorName}</p><p className="text-xs text-[#627086]">{e.createdAt}</p><p className="font-medium">{e.payload.title}</p>{[["내용",e.payload.text],["실행 결과",e.payload.response],["피드백",e.payload.feedback]].filter(([,v])=>v).map(([label,value])=><p key={label} className="whitespace-pre-wrap break-words"><span className="text-[#627086]">{label}: </span>{value}</p>)}</article>)}</DialogContent></Dialog>
  </>;
}

function useDraftClose(dirty:boolean,busy:boolean,onClose:()=>void) {
  const [confirm,setConfirm]=React.useState(false);
  React.useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue="";};window.addEventListener("beforeunload",warn);return()=>window.removeEventListener("beforeunload",warn);},[dirty]);
  return {request:()=>{if(!busy){if(dirty)setConfirm(true);else onClose();}},notice:confirm?<div role="alert" className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6"><p>저장하지 않은 내용이 있습니다. 계속 작성하거나 버리고 닫을 수 있습니다.</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setConfirm(false)}>계속 작성</Button><Button size="sm" variant="outline" onClick={onClose}>내용 버리고 닫기</Button></div></div>:null};
}
function StudentField({label,children}:{label:string;children:React.ReactNode}) {return <label className="grid gap-2 text-sm font-medium">{label}{children}</label>;}
function StudentEditor({entry,kind:initialKind,parent,onSave,busy,onClose}:{entry?:GuidanceEntry;kind:StudentKind;parent?:GuidanceEntry;onSave:StudentSave;busy:boolean;onClose:()=>void}) {
  const [kind,setKind]=React.useState(initialKind),[payload,setPayload]=React.useState<GuidancePayload>(()=>entry?.payload??guidancePayloadSchema.parse({title:"새 질문",text:"",parentKey:parent?.entityKey??"",origin:parent?"followup":"daily"}));
  const [title,setTitle]=React.useState(entry?.payload.title??""),[error,setError]=React.useState(""),[dirty,setDirty]=React.useState(false);const key=React.useRef(entry?.entityKey??clientId());
  const close=useDraftClose(dirty,busy,onClose);
  const put=<K extends keyof GuidancePayload>(k:K,v:GuidancePayload[K])=>{setDirty(true);setPayload(p=>({...p,[k]:v}));};
  const save=async(status:"draft"|"active")=>{setError("");try{await onSave({kind,entityKey:key.current,expectedRevision:entry?.revision??0,includeInWork:entry?.includeInWork??false,payload:{...payload,title,status}});onClose();}catch(e){setError(e instanceof Error?e.message:"저장하지 못했습니다.");}};
  return <Dialog open onOpenChange={open=>{if(!open)close.request();}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl" showCloseButton={!busy}><DialogHeader><DialogTitle>{entry?"기록 수정":"나의 기록 작성"}</DialogTitle><DialogDescription>본인의 말로 적어 주세요. 저장한 기록은 담당 선생님과 관리자도 확인할 수 있습니다.</DialogDescription></DialogHeader><fieldset disabled={busy} className="space-y-4">
    {!entry&&<StudentField label="어떤 기록인가요?"><select aria-label="기록 종류" className="min-h-10 rounded-lg border bg-white px-3 font-normal" value={kind} onChange={e=>{setKind(e.target.value as StudentKind);setDirty(true);}}>{Object.entries(studentKinds).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></StudentField>}
    {parent&&<p className="rounded-lg bg-[#f0f3fa] p-3 text-sm leading-6">이전 질문: {parent.payload.title}</p>}
    <StudentField label={kind==="question"?"어떤 점이 궁금한가요? · 필수":"기록 제목 · 필수"}><Input aria-label="기록 제목" maxLength={180} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true);}} placeholder="예: 같은 식물도 빛의 색에 따라 성장이 다를까?"/></StudentField>
    <StudentField label={kind==="correction"?"어떤 부분이 원문과 다른가요?":"궁금해진 이유·기록할 내용"}><Textarea aria-label="기록 내용" className="min-h-28" maxLength={8000} value={payload.text} onChange={e=>put("text",e.target.value)} placeholder={kind==="correction"?"화면 위치, 학생부 원문 쪽수와 함께 수정이 필요한 내용을 적어 주세요.":"수업·독서·활동에서 어떤 장면이나 개념이 질문으로 이어졌나요?"}/></StudentField>
    <div className="grid gap-4 sm:grid-cols-2"><StudentField label="관련 과목 · 선택"><Input aria-label="관련 과목" maxLength={150} value={payload.subject} onChange={e=>put("subject",e.target.value)}/></StudentField><StudentField label="목표일 · 선택"><Input aria-label="목표일" type="date" value={payload.dueDate} onChange={e=>put("dueDate",e.target.value)}/></StudentField></div>
    <details className="rounded-xl border p-4"><summary className="cursor-pointer text-sm font-medium">탐구 방법·알게 된 점·근거 더하기</summary><div className="mt-4 space-y-4">{([["method","어떻게 확인해 볼까요?",2000],["result","실제로 알게 된 점",3000],["remainingQuestion","새롭게 남은 질문",1500],["sourceNote","읽은 자료·활동 근거",1500]] as const).map(([key,label,max])=><StudentField key={key} label={label}><Textarea aria-label={label} maxLength={max} value={payload[key]} onChange={e=>put(key,e.target.value)}/></StudentField>)}</div></details>
  </fieldset>{error&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm leading-6 text-rose-800">{error} 입력 내용은 유지됩니다.</p>}{close.notice}<div className="flex flex-wrap justify-end gap-2"><Button variant="ghost" disabled={busy} onClick={close.request}>닫기</Button><Button variant="outline" disabled={busy||!title.trim()} onClick={()=>void save("draft")}>작성 중으로 저장</Button><Button disabled={busy||!title.trim()} onClick={()=>void save("active")}>{busy?"저장 중…":"기록 저장"}</Button></div></DialogContent></Dialog>;
}
function StudentReply({entry,onSave,busy,onClose}:{entry:GuidanceEntry;onSave:StudentSave;busy:boolean;onClose:()=>void}) {
 const [response,setResponse]=React.useState(entry.payload.response),[error,setError]=React.useState("");const close=useDraftClose(response!==entry.payload.response,busy,onClose);
 const submit=async()=>{setError("");try{await onSave({kind:entry.kind,entityKey:entry.entityKey,expectedRevision:entry.revision,intent:"submit",payload:{response}});onClose();}catch(e){setError(e instanceof Error?e.message:"제출하지 못했습니다.");}};
 return <Dialog open onOpenChange={open=>{if(!open)close.request();}}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl" showCloseButton={!busy}><DialogHeader><DialogTitle>선생님께 실행 결과 제출</DialogTitle><DialogDescription>{entry.payload.title}</DialogDescription></DialogHeader>{entry.payload.feedback&&<p className="whitespace-pre-wrap rounded-xl bg-[#eff4f1] p-4 text-sm leading-7 text-[#42634f]">선생님 피드백: {entry.payload.feedback}</p>}<StudentField label="무엇을 했고, 무엇이 달라졌나요? · 필수"><Textarea aria-label="제출할 실행 결과" disabled={busy} className="min-h-48" maxLength={5000} value={response} onChange={e=>setResponse(e.target.value)} placeholder="해 본 일 → 확인한 근거 → 달라진 생각 → 아직 남은 질문 순서로 적어 보세요."/></StudentField><p className="text-xs leading-6 text-[#627086]">제출하면 선생님의 확인 목록에 표시됩니다. 이전 제출 내용은 변경 이력에 남습니다.</p>{error&&<p role="alert" className="rounded-lg bg-rose-50 p-3 text-sm leading-6 text-rose-800">{error} 입력 내용은 유지됩니다.</p>}{close.notice}<div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={close.request}>닫기</Button><Button disabled={busy||!response.trim()} onClick={()=>void submit()}>{busy?"제출 중…":"결과 제출"}</Button></div></DialogContent></Dialog>;
}

export function StudentGuide({navigate}:{navigate:StudentNavigate}) {return <><StudentHeading title="사용 안내">짧게 기록하고 실제로 실행해 본 뒤, 선생님 피드백과 연결해 보세요.</StudentHeading><ol className={`${studentCard} list-decimal space-y-5 pl-10 text-base leading-7`}><li><span className="font-medium">오늘 할 일을 확인하세요.</span><p className="text-[#627086]">작성 중인 질문, 보완 요청, 목표일이 가까운 기록이 모여 있습니다.</p></li><li><span className="font-medium">질문과 실행 결과를 나눠 남기세요.</span><p className="text-[#627086]">‘내 질문·실행 기록’에서 먼저 기록을 저장한 후 ‘실행 결과 제출’을 누릅니다. 작성 중으로 저장한 내용도 담당 선생님과 관리자에게 공유됩니다.</p></li><li><span className="font-medium">피드백을 읽고 이어가세요.</span><p className="text-[#627086]">보완 요청에는 같은 기록에서 다시 제출합니다. 확인된 기록은 보존하고 ‘다음 질문 연결’로 새 탐구를 시작합니다.</p></li><li><span className="font-medium">나의 연구 흐름을 확인하세요.</span><p className="text-[#627086]">연구지문·교과 성적·활동별 기록·역량 점검·위키를 볼 수 있습니다. 분석은 선생님이 확인한 자료를 바탕으로 반영되며, 분석 결과는 학생부 원문이나 합격 가능성의 확정 판단이 아닙니다.</p></li><li><span className="font-medium">계획과 원문을 확인하세요.</span><p className="text-[#627086]">진학·과목 계획은 직접 기록할 수 있습니다. 평가 기준은 선생님이 적용한 자료를 사용합니다. 원본에 빠진 현재 학년 기록이 있으면 선생님에게 추가 등록을 요청하세요.</p></li></ol><section className={studentCard}><h2 className="text-lg font-semibold">분석이 원문과 다를 때</h2><p className="mt-3 text-base leading-7 text-[#627086]">기록 작성에서 ‘분석 정정 요청’을 고르고, 해당 화면과 원문 쪽수, 바뀌어야 할 내용을 적어 실행 결과로 제출하세요. 교사의 확인 후 수정된 분석이 반영됩니다.</p><Button className="mt-4" variant="outline" onClick={()=>navigate("journal","new")}>기록 작성으로</Button></section></>;}
