"use client";

import * as React from "react";
import { ArrowUpRight, CheckCircle2, ClipboardCheck, FileText, Search, Upload, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { studentReadiness } from "@/lib/portal-workflow";
import { guidanceKinds, guidanceStatuses } from "@/lib/guidance";
import { teacherOverview, teacherStudents, type TeacherView, type TeacherFilter } from "@/lib/teacher-overview";
import type { PortalData, Student } from "@/lib/portal-types";

export type TeacherNavigate = (view:TeacherView,studentId?:number,entryKey?:string)=>void;
export const teacherSelect="h-11 min-w-0 rounded-lg border border-[#d6e2df] bg-white px-3 text-sm focus:outline-2 focus:outline-[#167666]";
const panel="rounded-2xl border border-[#dfe7e4] bg-white p-5 sm:p-6";
export function TeacherHome({data,students,navigate,onFilter}:{data:PortalData;students:Student[];navigate:TeacherNavigate;onFilter:(filter:TeacherFilter)=>void}) {
  const stats=teacherOverview(data,students);
  return <div className="space-y-6">
    <section className="rounded-2xl bg-[#153f3b] px-6 py-7 text-white sm:px-8"><p className="text-sm text-[#a6d2c6]">우리 반의 질문이 다음 탐구로 이어지도록</p><h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">오늘의 학급 지도</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-[#d0e4dd]">학생이 제출한 설명과 근거를 확인하고, 다음 질문을 함께 정합니다. 원본에서 시작해 상담과 연구 흐름을 한곳에 쌓아갑니다.</p><div className="mt-5 flex flex-wrap gap-2"><Button className="bg-[#d8f2e8] text-[#153f3b] hover:bg-white" onClick={()=>navigate("inbox")}>확인할 상담 {stats.queue.length}건<ArrowUpRight/></Button><Button variant="outline" className="border-white/25 bg-transparent text-white hover:bg-white/10 hover:text-white" onClick={()=>navigate("students")}>담당 학생 보기</Button></div></section>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[
      {label:"담당 재학생",value:stats.active,note:"현재 선택한 학급 범위",icon:Users,click:()=>onFilter("all")},
      {label:"제출 확인 대기",value:stats.submitted,note:"학생이 결과를 제출한 기록",icon:ClipboardCheck,click:()=>navigate("inbox")},
      {label:"원본 보완 필요",value:stats.missingRecords.length,note:"필요한 이전 학년 자료 확인",icon:FileText,click:()=>onFilter("missingRecords")},
      {label:"분석 준비·갱신",value:stats.analysis.length,note:"분석 없음 또는 미반영 원본",icon:Upload,click:()=>onFilter("analysis")},
    ].map(m=><button key={m.label} onClick={m.click} className={`${panel} text-left transition hover:border-[#86b5a7] focus-visible:outline-2 focus-visible:outline-[#167666]`}><div className="flex items-center justify-between text-sm text-[#536e65]">{m.label}<m.icon className="size-4"/></div><p className="mt-3 text-3xl font-semibold tabular-nums">{m.value}<span className="ml-1 text-sm font-normal text-[#73867e]">{m.label==="제출 확인 대기"?"건":"명"}</span></p><p className="mt-2 text-xs leading-5 text-[#73867e]">{m.note}</p></button>)}</div>
    <div className="grid items-start gap-6 xl:grid-cols-[1.5fr_1fr]"><section className={panel}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h2 className="text-lg font-semibold">먼저 확인할 기록</h2><Button variant="ghost" size="sm" onClick={()=>navigate("inbox")}>전체 {stats.queue.length}건<ArrowUpRight/></Button></div><QueueRows data={data} rows={stats.queue.slice(0,5)} navigate={navigate}/></section><section className={panel}><h2 className="text-lg font-semibold">지도 준비 체크</h2><div className="mt-4 divide-y divide-[#e7edea]">{[
      {label:"분석 정정 요청",count:stats.corrections,action:()=>navigate("inbox")},
      {label:"확인일이 지난 기록",count:stats.overdue,action:()=>navigate("inbox")},
      {label:"평가 기준 재점검",count:stats.referenceChecks.length,action:()=>navigate("inbox")},
      {label:"학생 계정 연결 대기",count:stats.unlinked.length,action:()=>onFilter("unlinked")},
    ].map(r=><button key={r.label} className="flex w-full items-center gap-3 py-4 text-left text-sm hover:text-[#117766]" onClick={r.action}><span className="flex-1">{r.label}</span><span className="font-semibold tabular-nums">{r.count}</span><ArrowUpRight className="size-4"/></button>)}</div><p className="mt-3 text-xs leading-6 text-[#73867e]">필요 자료는 2학년의 경우 1학년, 3학년의 경우 1·2학년입니다. 현재 학년 내용이 있는 원본도 함께 분석합니다.</p></section></div>
  </div>;
}
function QueueRows({data,rows,navigate}:{data:PortalData;rows:ReturnType<typeof teacherOverview>["queue"];navigate:TeacherNavigate}) {
  if(!rows.length)return <div className="rounded-xl bg-[#f6f9f7] p-6 text-sm leading-7 text-[#60776d]"><CheckCircle2 className="mb-2 size-5"/>현재 조건에 해당하는 확인 대기 기록이 없습니다.</div>;
  return <div className="divide-y divide-[#e7edea]">{rows.map(({entry,submitted,correction,overdue})=>{
    const student=data.students.find(s=>s.id===entry.studentId);
    return <button key={entry.entityKey} onClick={()=>navigate("guidance",entry.studentId!,entry.entityKey)} className="flex w-full items-center gap-3 py-4 text-left hover:text-[#117766]"><div className="min-w-0 flex-1"><div className="mb-2 flex flex-wrap gap-2 text-xs"><Badge variant="outline">{guidanceKinds[entry.kind]}</Badge>{submitted&&<Badge variant="secondary">교사 확인 대기</Badge>}{correction&&<Badge variant="outline">정정 요청</Badge>}{overdue&&<Badge className="bg-amber-50 text-amber-900">확인일 지남</Badge>}{entry.audience==="staff"&&<Badge variant="outline">교직원만</Badge>}</div><p className="break-words font-medium">{entry.payload.title}</p><p className="mt-2 text-xs text-[#64796f]">{student?.name} · {student?.studentNumber} · {guidanceStatuses[entry.payload.status]}{entry.payload.dueDate&&` · 확인일 ${entry.payload.dueDate}`}</p></div><ArrowUpRight className="size-4 shrink-0"/></button>;
  })}</div>;
}
export function TeacherInbox({data,students,navigate}:{data:PortalData;students:Student[];navigate:TeacherNavigate}) {
  const [filter,setFilter]=React.useState("all"),[page,setPage]=React.useState(1);
  const stats=teacherOverview(data,students),rows=stats.queue.filter(q=>filter==="submitted"?q.submitted:filter==="correction"?q.correction:filter==="overdue"?q.overdue:true);
  React.useEffect(()=>setPage(1),[filter,students.map(s=>s.id).join(",")]);
  const pages=Math.max(1,Math.ceil(rows.length/20)),current=Math.min(page,pages);
  return <div className="space-y-5"><div><h1 className="text-3xl font-semibold">확인할 상담</h1><p className="mt-3 text-sm leading-7 text-[#64796f]">제출된 결과, 정정 요청, 확인일이 지난 기록을 확인합니다. 기록을 누르면 해당 학생의 원문과 피드백 화면이 열립니다.</p></div><div className="flex flex-wrap gap-2">{[["all","전체",stats.queue.length],["submitted","제출 확인 대기",stats.submitted],["correction","정정 요청",stats.corrections],["overdue","확인일 지남",stats.overdue]].map(([key,label,count])=><Button key={key} variant={filter===key?"default":"outline"} onClick={()=>setFilter(String(key))}>{label} {count}</Button>)}</div><section className={panel}><QueueRows data={data} rows={rows.slice((current-1)*20,current*20)} navigate={navigate}/><Pager page={current} pages={pages} total={rows.length} onChange={setPage}/></section>{stats.referenceChecks.length>0&&<section className={panel}><h2 className="mb-3 text-lg font-semibold">분석에 적용한 평가 기준 재점검</h2><div className="divide-y">{stats.referenceChecks.map((c,i)=><button key={`${c.studentId}:${c.sourceKey}:${i}`} onClick={()=>navigate("evaluation",c.studentId)} className="block w-full py-4 text-left text-sm"><p className="font-semibold">{data.students.find(s=>s.id===c.studentId)?.name} · {c.title}</p><p className="mt-2 leading-6 text-[#64796f]">{c.reasons.join(" ")}</p></button>)}</div></section>}</div>;
}
export function TeacherStudents({data,students,navigate,filter,setFilter,onAdd,onBulk,disabled}:{data:PortalData;students:Student[];navigate:TeacherNavigate;filter:TeacherFilter;setFilter:(f:TeacherFilter)=>void;onAdd:()=>void;onBulk:()=>void;disabled:boolean}) {
  const [query,setQuery]=React.useState(""),[status,setStatus]=React.useState("active"),[page,setPage]=React.useState(1);
  React.useEffect(()=>setPage(1),[query,status,filter,students.map(s=>s.id).join(",")]);
  const rows=teacherStudents({...data,students},{examples:true,status,query,filter}),pages=Math.max(1,Math.ceil(rows.length/30)),current=Math.min(page,pages);
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">담당 학생</h1><p className="mt-3 text-sm leading-7 text-[#64796f]">자료 준비 상태를 살펴보고 학생의 상담과 연구 기록으로 이동합니다.</p></div><div className="flex gap-2"><Button variant="outline" disabled={disabled||!data.classes.length} onClick={onAdd}>학생 한 명 등록</Button><Button disabled={disabled||!data.classes.length} onClick={onBulk}><Upload/>엑셀로 여러 명 등록</Button></div></div><section className={panel}><div className="flex flex-wrap gap-3"><div className="relative min-w-52 flex-1"><Search className="absolute left-3 top-3.5 size-4 text-[#73867e]"/><Input className="h-11 pl-9" aria-label="담당 학생 검색" placeholder="이름, 학번, 이메일, 연구 키워드" value={query} onChange={e=>setQuery(e.target.value)}/></div><select aria-label="학생 상태" className={teacherSelect} value={status} onChange={e=>setStatus(e.target.value)}><option value="active">재학생</option><option value="graduated">졸업생</option><option value="archived">보관 학생</option><option value="all">모든 상태</option></select><select aria-label="자료 준비 필터" className={teacherSelect} value={filter} onChange={e=>setFilter(e.target.value as TeacherFilter)}><option value="all">자료 상태 전체</option><option value="missingRecords">원본 보완 필요</option><option value="analysis">분석 준비·갱신</option><option value="unlinked">계정 연결 대기</option></select></div><p className="mt-4 text-xs text-[#64796f]">{rows.length}명 · 졸업·학급 이동·계정 승인은 관리자 화면에서 처리합니다.</p></section>
    <div className="space-y-3">{!rows.length&&<section className={panel}><p className="text-sm leading-7 text-[#64796f]">조건에 맞는 학생이 없습니다. 검색어와 필터를 확인하거나 담당 학급에 학생을 등록하세요.</p></section>}{rows.slice((current-1)*30,current*30).map(s=>{const ready=studentReadiness(data,s),pending=data.records.filter(r=>r.studentId===s.id&&r.processingStatus==="source_only").length;return <article key={s.id} className={`${panel} flex flex-wrap items-center gap-5`}><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{s.name}</h2><span className="text-sm text-[#64796f]">{s.studentNumber}</span>{s.isExample&&<Badge variant="outline">예시</Badge>}{s.status!=="active"&&<Badge variant="secondary">{s.status==="graduated"?"졸업생":"보관 학생"}</Badge>}</div><p className="mt-1 text-xs text-[#64796f]">{ready.classroom?.schoolYear}학년도 · {ready.classroom?.name} · {s.userId?"계정 연결됨":"계정 연결 대기"}</p><div className="mt-3 flex flex-wrap gap-2"><Badge variant="outline">{ready.missingGrades.length?`${ready.missingGrades.join("·")}학년 원본 필요`:"이전 학년 원본 준비됨"}</Badge>{ready.currentGradeIncluded&&<Badge variant="outline">현재 학년 내용 포함</Badge>}<Badge variant="secondary">{ready.profile?ready.profile.versionLabel:"분석 결과 없음"}</Badge>{pending>0&&<Badge variant="outline">미반영 원본 {pending}건</Badge>}</div>{ready.profile&&<p className="mt-3 line-clamp-2 text-sm leading-6 text-[#64796f]">{ready.profile.oneLineProfile}</p>}</div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={()=>navigate("guidance",s.id)}>상담·피드백</Button><Button variant="outline" size="sm" onClick={()=>navigate("records",s.id)}>원본</Button><Button variant="outline" size="sm" onClick={()=>navigate("import",s.id)}>Work</Button><Button size="sm" onClick={()=>navigate("fingerprint",s.id)}>연구 기록<ArrowUpRight/></Button></div></article>;})}</div><Pager page={current} pages={pages} total={rows.length} onChange={setPage}/>
  </div>;
}
function Pager({page,pages,total,onChange}:{page:number;pages:number;total:number;onChange:(p:number)=>void}) {return <div className="mt-4 flex items-center justify-end gap-3 text-sm text-[#64796f]"><span>{total}건 · {page} / {pages}</span><Button variant="outline" size="sm" disabled={page<=1} onClick={()=>onChange(page-1)}>이전</Button><Button variant="outline" size="sm" disabled={page>=pages} onClick={()=>onChange(page+1)}>다음</Button></div>;}
export function TeacherGuide({adminUrl,navigate}:{adminUrl:string|null;navigate:TeacherNavigate}) {
  return <section className={`${panel} space-y-6`}><h1 className="text-3xl font-semibold">교사 사용 안내</h1><ol className="list-decimal space-y-5 pl-5 text-sm leading-7">{[
    ["담당 학급 확인","관리자가 교사 계정을 승인하고 담당 학급을 배정하면 학생 목록이 보입니다. 처음 이 사이트에 로그인한 계정은 관리자의 사이트 계정 연결 승인이 필요합니다."],
    ["학생과 원본 준비","담당 학생에서 엑셀 양식을 내려받아 여러 학생을 등록할 수 있습니다. 학생부 원본은 포함된 학년을 모두 지정해 올리세요. 2학년 내용, 3학년 내용이 있는 경우에도 빠짐없이 포함합니다."],
    ["Work 분석과 반영","공용 평가 자료실에서 필요한 자료를 선택해 저장하고 자료 묶음을 받습니다. Work 결과에서 학생별 요청문과 원본 묶음을 받아 이 Work에서 분석한 뒤 결과 JSON을 검토하고 반영합니다."],
    ["연구 기록 확인","교과·성적의 꺾은선 그래프, 활동 모아보기, 연구지문, 역량 점검, LLM 위키와 진학·과목 계획을 확인합니다. 근거가 없는 내용은 원본과 대조하고 정정 기록을 남깁니다."],
    ["상담과 피드백 누적","확인할 상담에서 제출된 기록을 엽니다. 관찰 사실과 해석을 나눠 쓰고, 학생에게 공개할지 교직원만 볼지 선택하세요. 피드백은 이전 내용을 보존하면서 새 이력으로 저장됩니다."],
  ].map(([title,text])=><li key={title}><p className="font-semibold">{title}</p><p className="mt-1 text-[#64796f]">{text}</p></li>)}</ol><div className="rounded-xl bg-[#f3f7f4] p-5 text-sm leading-7"><p>학급 배정, 교사 승인, 계정 연결, 학생 학급 이동·졸업, 공용 자료 등록·판본 승인은 관리자가 처리합니다. 자료 저장이 막히면 연결 상태와 계정 승인을 확인해 주세요.</p>{adminUrl&&<a className="mt-3 inline-block font-medium text-[#117766] underline" href={adminUrl} target="_blank" rel="noreferrer">관리자 사이트 주소</a>}</div><Button onClick={()=>navigate("home")}>학급 지도 시작하기</Button></section>;
}
